import React, { createContext, useContext, useMemo, useState } from 'react'

const translations = {
  en: {
    userReportUser: 'User',
    loadingUsersReport: 'Loading users report…',
    usersActivitySubtitle: 'User activity and platform usage overview',
    userActivity: 'User Activity',
    userActivitySubtitle: 'Ride activity and spending by user',
    noUsersMatch: 'No users match the selected filters.',
    registered: 'Registered',
    safetyTitle: 'Safety',
    safetySubtitle: 'Emergency controls & safety operations',
    emergencyAlerts: 'Emergency Alerts',
    emergencyAlertsDescription: 'View and manage emergency alerts',
    policeStations: 'Police Stations',
    policeStationsDescription: 'Manage nearby police stations',
    safetySettings: 'Safety Settings',
    safetySettingsDescription: 'Configure safety features',
    emergencyContacts: 'Emergency Contacts',
    emergencyContactsDescription: 'Manage emergency contacts',
    blockedUsersDescription: 'View blocked users list',
    safetyAndEmergency: 'Safety & Emergency',
    safetyControlCenter: 'Safety Control Center',
    monitorEmergencyAlarms: 'Monitor emergency alarms, manage rider safety events and review driver allocation rules.',
    safetySystem: 'Safety system',
    emergencyAlarm: 'Emergency alarm',
    unknownRider: 'Unknown rider',
    unknownStatus: 'Unknown',
    acknowledge: 'Acknowledge',
    resolveCallPolice: 'Resolve & Call Police',
    noEmergencyAlerts: 'No emergency alerts',
    noEmergencyAlertsDescription: 'There are currently no rider safety events requiring attention.',
    availablePoliceContacts: 'Available police contacts for emergency response.',
    noPoliceStationData: 'No police station data available.',
    call: 'Call',
    safetyConfiguration: 'Safety Configuration',
    driverAllocationRules: 'Driver Allocation Rules',
    ruleActive: 'Rule Active',
    passenger: 'Passenger',
    femalePassenger: 'Female passenger',
    requestsBikeRide: 'Requests a Bike ride.',
    driverAllocation: 'Driver Allocation',
    femaleDriverOnly: 'Female driver only',
    eligibleFemaleDriversOnly: 'Eligible female drivers only',
    activeAllocationRule: 'Active allocation rule',
    femalePassengerBikeRule: 'Female passenger + Bike ride → Female driver only.',
    femalePassengerBikeDescription: 'Female passengers requesting bike rides are automatically assigned only to eligible female drivers.',
    blockedUsersTitle: 'Blocked Users',
    blockedUsersEmpty: 'Blocked users',
    blockedUsersNotConfigured: 'Blocked user management is not configured in the current Safety data source.',
    rideEasySupport: 'RideEasy Support',
    rideEasySupportDescription: 'Manage the emergency and customer support contact.',
    loadingRideEasySupport: 'Loading RideEasy Support...',
    supportStatus: 'Support status',
    supportActive: 'RideEasy Support is currently active.',
    supportInactive: 'RideEasy Support is currently inactive.',
    name: 'Name',
    phone: 'Phone',
    description: 'Description',
    supportChangesUpdate: 'Changes will update the existing RideEasy Support record.',
    supportRecordCreated: 'A RideEasy Support record will be created.',
    saving: 'Saving...',
    saveSupport: 'Save Support',
    failedLoadSupport: 'Failed to load RideEasy Support.',
    supportUpdatedSuccessfully: 'RideEasy Support updated successfully.',
    failedUpdateSupport: 'Failed to update RideEasy Support.',

    helpSupport: 'Help & Support',
    reportsPageTitle: 'Reports',
    reportsPageSubtitle: 'View platform analytics & reports',

    loadingDriversReport: 'Loading drivers report…',
    driversActivitySubtitle: 'Driver activity and performance overview',
    driverPerformance: 'Driver Performance',
    driverPerformanceSubtitle: 'Driver activity, completed rides and earnings',
    noDriverRecords: 'No driver records found.',
    approval: 'Approval',
    earnings: 'Earnings',    loadingBookingsReport: 'Loading bookings report…',
    bookingsActivitySubtitle: 'Booking activity and ride status overview',
    bookingDetails: 'Booking Details',
    bookingDetailsSubtitle: 'Ride, rider, driver and fare information',
    noBookingsFound: 'No bookings found',
    loadingEarningsReport: 'Loading earnings report…',
    fromCompletedRides: 'From completed rides',
    recordedCaptainEarnings: 'Recorded captain earnings',
    recordedPlatformFees: 'Recorded platform fees',
    appliedToCompletedRides: 'Applied to completed rides',
    completedRidesIncluded: 'Completed rides included in this report',
    noCompletedRideEarnings: 'No completed ride earnings found',
    tryAnotherDateRange: 'Try another date range.',
    earningsReport: 'Earnings Report',
    earningsReportDescription: 'View earnings analytics',
    bookingsReport: 'Bookings Report',
    bookingsReportDescription: 'View bookings analytics',
    driversReport: 'Drivers Report',
    driversReportDescription: 'View driver performance',
    usersReport: 'Users Report',
    usersReportDescription: 'View users analytics',
    downloadReports: 'Download Reports',
    downloadReportsDescription: 'Download data in CSV',
    backToReports: 'Back to Reports',
    revenueAndEarningsOverview: 'Revenue and earnings overview from completed rides',
    allTime: 'All time',
    last7Days: 'Last 7 days',
    last30Days: 'Last 30 days',
    last90Days: 'Last 90 days',
    totalRevenue: 'Total Revenue',
    platformFee: 'Platform Fee',
    discounts: 'Discounts',
    rideEarnings: 'Ride Earnings',
    fare: 'Fare',
    totalBookings: 'Total Bookings',
    completed: 'Completed',
    ongoing: 'Ongoing',
    cancelled: 'Cancelled',
    bookingValue: 'Booking Value',
    allStatuses: 'All statuses',
    started: 'Started',
    accepted: 'Accepted',
    pending: 'Pending',
    rider: 'Rider',
    driver: 'Driver',
    vehicle: 'Vehicle',
    route: 'Route',
    allDrivers: 'All drivers',
    online: 'Online',
    offline: 'Offline',
    busy: 'Busy',
    totalDrivers: 'Total Drivers',
    onlineDrivers: 'Online Drivers',
    offlineDrivers: 'Offline Drivers',
    approvedDrivers: 'Approved Drivers',
    completedRides: 'Completed Rides',
    searchDriver: 'Search driver, phone, vehicle or city...',
    approved: 'Approved',
    usersReportSearch: 'Search user, email, phone or city...',
    allUsers: 'All users',
    active: 'Active',
    blocked: 'Blocked',
    totalUsers: 'Total Users',
    activeUsers: 'Active Users',
    blockedUsers: 'Blocked Users',
    totalRides: 'Total Rides',
    userSpending: 'User Spending',
    spending: 'Spending',
    cancelledRidesInSelectedPeriod: 'Cancelled rides in selected period',

    helpSupportSubtitle: 'Get help and support',
    needHelp: 'Need help?',
    needHelpText: 'If you are facing an issue with the RideEasy Admin Panel, contact the support team for assistance.',
    adminSupport: 'Admin Support',
    adminSupportText: 'For account, dashboard, driver, booking or payment related issues, contact the RideEasy administration team.',
    contactSupport: 'Contact Support',
    contactSupportText: 'Support contact details will be available here.',
    supportCasesSubtitle: 'Review and investigate user & driver support cases',
    supportCases: 'Support Cases',
    caseShown: 'case shown',
    casesShown: 'cases shown',
    searchSupportCases: 'Search case, ride, user or category...',
    supportAll: 'All',
    supportUser: 'User',
    supportDriver: 'Driver',
    supportOpen: 'Open',
    supportInReview: 'In Review',
    supportEscalated: 'Escalated',
    supportResolved: 'Resolved',
    loadingSupportCases: 'Loading support cases...',
    unableLoadSupportCases: 'Unable to load support cases',
    noSupportCases: 'No support cases found',
    tryAnotherSearchFilter: 'Try another search or filter.',
    caseLabel: 'Case',
    closeCaseDetails: 'Close case details',
    priorityLabel: 'Priority',
    subject: 'Subject',
    userDriver: 'User / Driver',
    rideIdLabel: 'Ride ID',
    rideStatus: 'Ride Status',
    cancellationReason: 'Cancellation Reason',
    cancellationFee: 'Cancellation Fee',
    assignedOwner: 'Assigned Owner',
    investigationContext: 'Investigation Context',
    statusHistory: 'Status History',
    caseCreated: 'Case created',
    currentStatus: 'Current status',
    statusTransitionUnavailable: 'Status transition timestamp unavailable',
    supportHigh: 'High',
    supportMedium: 'Medium',
    supportLow: 'Low',
    supportPriority: 'Priority',



    invoicesPageTitle: 'Invoices',
    invoicesPageSubtitle: 'View ride invoices, fare totals and linked payment information.',
    platformRevenue: 'Platform Revenue',
    totalPaidAmount: 'Total paid amount',
    platformCommission: 'Platform Commission',
    platformFeeEarned: 'Platform fee earned',
    driverShare: 'Driver Share',
    driverEarnings: 'Driver earnings',
    pendingPayouts: 'Pending Payouts',
    driverSettlementsPending: 'Driver settlements pending',
    invoiceDetail: 'Invoice Detail',
    invoiceInformation: 'Invoice Information',
    paymentLinkage: 'Payment Linkage',
    fareAndTotal: 'Fare & Total',
    authoritativeInvoiceTotal: 'Authoritative Invoice Total',
    invoiceList: 'Invoice List',
    invoiceTotalSource: 'Invoice total is sourced from the authoritative ride amount.',
    searchInvoice: 'Search invoice, ride, customer, amount…',
    loadingInvoices: 'Loading invoices…',
    noRideInvoices: 'No ride invoices available.',
    noInvoicesMatch: 'No invoices match your search.',
    invoice: 'Invoice',
    rideId: 'Ride ID',
    created: 'Created',
    paymentId: 'Payment ID',
    providerReference: 'Provider Reference',
    fareConfigurationTitle: 'Fare Configuration',
    configureVersionedFares: 'Configure versioned fares by ride category and city / zone with controlled effective periods.',
    fareVersions: 'Fare versions',
    editDraftFare: 'Edit Draft Fare',
    createFareConfiguration: 'Create Fare Configuration',
    activeHistoricalVersions: 'Active and historical versions cannot be silently rewritten.',
    cancelEdit: 'Cancel Edit',
    rideTypeLabel: 'Ride Type',
    cityZoneLabel: 'City / Zone',
    distanceRate: 'Distance Rate / km',
    timeRate: 'Time Rate / min',
    minimumFare: 'Minimum Fare',
    fees: 'Fees',
    registrationFee: 'Registration Fee',
    minimumWalletBalance: 'Minimum Wallet Balance',
    taxPercentage: 'Tax (%)',
    effectiveFrom: 'Effective From',
    effectiveTo: 'Effective To',
    saveAsDraft: 'Save as Draft',
    activationDescription: 'Activation is a separate confirmed action and is validated against overlapping active periods.',
    calculating: 'Calculating…',
    previewFare: 'Preview Fare',
    updateDraft: 'Update Draft',
    createDraft: 'Create Draft',
    farePreview: 'Fare Preview',
    fareConfigurationList: 'Fare Configuration List',
    fareConfigurationListSubtitle: 'Ride type, city / zone, version, status and effective period.',
    version: 'Version',
    noFareConfigurations: 'No fare configurations found.',
    edit: 'Edit',
    activate: 'Activate',
    deactivate: 'Deactivate',
    history: 'History',
    loadingFareConfigurations: 'Loading fare configurations…',
    cityZonePlaceholder: 'e.g. Pune / Zone 1',
    openEnded: 'Open ended',
    invalidDate: 'Invalid date',
    baseFareRequired: 'Base fare is required.',
    distanceRateRequired: 'Distance rate is required.',
    timeRateRequired: 'Time rate is required.',
    minimumFareRequired: 'Minimum fare is required.',
    feesRequired: 'Fees are required.',
    registrationFeeRequired: 'Registration fee is required.',
    minimumWalletBalanceRequired: 'Minimum wallet balance is required.',
    taxRequired: 'Tax is required.',
    cityZoneRequired: 'City / zone is required.',
    validNumber: 'must be a valid number.',
    cannotBeNegative: 'cannot be negative.',
    effectiveFromRequired: 'Effective from is required.',
    effectiveFromInvalid: 'Effective from is invalid.',
    effectiveToInvalid: 'Effective to is invalid.',
    effectiveToAfterFrom: 'Effective to must be after effective from.',
    unableToSaveFareConfiguration: 'Unable to save fare configuration.',
    draftOnlyEdit: 'Only draft configurations can be edited. Active and historical versions remain unchanged.',
    publishFare: 'Publish',
    oldBaseFare: 'Old Base Fare',
    newBaseFare: 'New Base Fare',
    oldDistanceRate: 'Old Distance Rate',
    newDistanceRate: 'New Distance Rate',
    oldMinimumFare: 'Old Minimum Fare',
    newMinimumFare: 'New Minimum Fare',
    deactivateFare: 'Deactivate',
    unableToUpdateFareStatus: 'Unable to update fare status.',
    unableToLoadFareHistory: 'Unable to load fare history.',
    sampleDistance: 'Sample distance in km:',
    sampleRideTime: 'Sample ride time in minutes:',
    sampleDistanceTimeInvalid: 'Sample distance and time must be valid non-negative numbers.',
    unableToCalculateFarePreview: 'Unable to calculate fare preview.',
    baseFare: 'Base Fare',
    discount: 'Discount',
    paymentAmount: 'Payment Amount',
    date: 'Date',
    payment: 'Payment',
    total: 'Total',
    status: 'Status',
    action: 'Action',
    ride: 'Ride',
    dashboard: 'Dashboard',
    users: 'Users',
    drivers: 'Drivers',
    vehicles: 'Vehicles',
    manageRegisteredVehicles: 'Manage registered vehicles and verification status',
    allVehicles: 'All Vehicles',
    searchVehicles: 'Search vehicle number, type, model or driver...',
    vehicleStatusLabel: 'Status',
    noVehiclesFound: 'No vehicles found',
    noVehiclesMatch: 'No vehicles match your current search or filter.',
    loadingVehicles: 'Loading vehicles...',
    vehicleDetails: 'Vehicle Details',
    unnamedDriver: 'Unnamed driver',
    vehicleModel: 'Vehicle Model',
    driverEmail: 'Driver Email',
    driverPhone: 'Driver Phone',
    rcStatus: 'RC Status',
    insuranceStatus: 'Insurance Status',
    registrationDate: 'Registration Date',
    vehicleStatus: 'Vehicle Status',
    pendingVerification: 'Pending Verification',
    vehicleColumn: 'Vehicle',
    modelColumn: 'Model',
    driverColumn: 'Driver',
    vehicleRecordsSource: 'Vehicle records are sourced from registered drivers.',

    verification: 'Verification',
    verificationQueue: 'Verification Queue',
    valid: 'Valid',
    expiringSoon: 'Expiring soon',
    reviewDriverVerificationInfo: 'Review driver verification information',
    verificationDocuments: 'Verification Documents',
    documentReview: 'Document review',
    statusLabel: 'Status',
    versionLabel: 'Version',
    documentInformation: 'Document Information',
    noExtractedDocumentInformation: 'No extracted document information',
    apiDidNotProvideDocumentFields: 'The API did not provide additional document fields.',
    documentPreview: 'Document Preview',
    openDocument: 'Open',
    loadingDocumentPreview: 'Loading document preview...',
    previewUnavailable: 'Preview unavailable',
    authorizedDocumentPreviewUnavailable: 'The authorized document preview could not be loaded.',
    back: 'Back',
    unableToLoadVerificationQueue: 'Unable to load verification queue',
    rejectVerification: 'Reject Verification',
    unableToLoadDocumentPreview: 'Unable to load document preview',
    viewDocuments: 'View Documents',
    noDocumentsReturned: 'The driver API did not return document records for this driver.',
    noDocumentsAvailable: 'No documents available',
    uploadDocument: 'Upload Document',
    notSubmitted: 'Not Submitted',
    submitted: 'Submitted',
    psychologicalAssessment: 'Psychological Assessment',
    eyeExamination: 'Eye Examination',
    medicalFitness: 'Medical Fitness',
    policeVerification: 'Police Verification',
    reviewCompliance: "Review the driver's mandatory compliance requirements.",
    captainCompliance: 'Captain Compliance',
    rejectionReason: 'Rejection Reason',
    subscriptionExpiry: 'Subscription Expiry',
    overallStatus: 'Overall Status',
    lastUpdated: 'Last Updated',
    licence: 'Licence',
    vehicleNumber: 'Vehicle Number',
    vehicleType: 'Vehicle Type',
    driverDetails: 'Driver Details',
    reviewVerificationRequests: 'Review driver verification requests and submitted documents.',
    rides: 'Rides',
    liveOperations: 'Live Operations',
    liveOpsPageSubtitle: 'Monitor driver availability and active ride status.',
    liveOpsUpdatesConnected: 'Live updates connected',
    liveOpsReconnecting: 'Reconnecting live updates…',
    liveOpsUpdatesDisabled: 'Live updates disabled',
    liveOpsUpdatesDisconnected: 'Live updates disconnected',
    liveOpsAvailableDrivers: 'Available drivers',
    liveOpsDriversOnActiveRides: 'Drivers on active rides',
    liveOpsCurrentlyUnavailable: 'Currently unavailable',
    liveOpsLiveMap: 'Live Map',
    liveOpsLive: 'Live',
    liveOpsStale: 'Stale',
    liveOpsDriverActiveLocations: 'Driver and active ride locations',
    liveOpsLoadingMap: 'Loading live map...',
    liveOpsFetchingLocations: 'Fetching driver and active ride locations.',
    liveOpsUnableLoadMap: 'Unable to load live map',
    liveOpsLocationsCouldNotLoad: 'Driver and active ride locations could not be loaded.',
    liveOpsNoLocations: 'No live locations available',
    liveOpsLocationsAppearHere: 'Driver and active ride locations will appear here.',
    liveOpsDriverStatus: 'Driver Status',
    liveOpsDriver: 'driver',
    liveOpsDrivers: 'drivers',
    liveOpsShown: 'shown',
    liveOpsSearchDriver: 'Search driver...',
    liveOpsAllStatuses: 'All statuses',
    liveOpsLoadingStatus: 'Loading driver status...',
    liveOpsTryAgain: 'Try again',
    liveOpsNoDrivers: 'No drivers found',
    liveOpsChangeFilter: 'Try changing your search or status filter.',
    liveOpsUnnamedDriver: 'Unnamed Driver',
    liveOpsNoContact: 'No contact',
    liveOpsVehicle: 'Vehicle',
    liveOpsStatus: 'Status',
    liveOpsOnline: 'Online',
    liveOpsBusy: 'Busy',
    liveOpsOffline: 'Offline',
    liveOpsUnableLoadDrivers: 'Unable to load driver live status.',

    couponPageTitle: 'Coupons',
    couponPageSubtitle: 'Create and manage promotional coupons.',
    couponCreate: 'Create Coupon',
    couponSearch: 'Search coupon code...',
    couponAllStatus: 'All Status',
    couponActive: 'Active',
    couponExpired: 'Expired',
    couponCode: 'Coupon Code',
    couponDiscount: 'Discount',
    couponMinRide: 'Min. Ride',
    couponValidity: 'Validity',
    couponUsage: 'Usage',
    couponStatus: 'Status',
    couponActions: 'Actions',
    couponEdit: 'Edit',
    couponDelete: 'Delete',
    couponNoCoupons: 'No coupons found.',
    couponEditTitle: 'Edit Coupon',
    couponCreateTitle: 'Create Coupon',
    couponUpdateDetails: 'Update coupon details.',
    couponCreateForRiders: 'Create a promotional coupon for riders.',
    couponCodeRequired: 'Coupon Code *',
    couponDiscountTypeRequired: 'Discount Type *',
    couponPercentage: 'Percentage (%)',
    couponFixedAmount: 'Fixed Amount (₹)',
    couponDiscountValueRequired: 'Discount Value *',
    couponMinimumRideRequired: 'Minimum Ride Amount *',
    couponMaximumDiscount: 'Maximum Discount',
    couponValidFromRequired: 'Valid From *',
    couponValidUntilRequired: 'Valid Until *',
    couponUsageLimitRequired: 'Usage Limit *',
    couponCancel: 'Cancel',
    couponUpdate: 'Update Coupon',
    couponSave: 'Save Coupon',
    couponFillRequired: 'Please fill all required fields.',
    couponLoadFailed: 'Failed to load coupons.',
    couponSaveFailed: 'Failed to save coupon.',
    couponDeleteFailed: 'Failed to delete coupon.',
    couponDeleteConfirm: 'Delete coupon',
    couponExample: 'e.g.',

    finance: 'Finance',
    coupons: 'Coupons',
    payments: 'Payments',
    sos: 'SOS',
    support: 'Support',
    reports: 'Reports',
    auditLogs: 'Audit Logs',
    auditLogsSubtitle: 'Review administrative and system activity.',
    allActors: 'All Actors',
    actor: 'Actor',
    actorType: 'Actor Type',
    allTargets: 'All Targets',
    target: 'Target',
    timestamp: 'Timestamp',
    loadingAuditLogs: 'Loading audit logs…',
    failedToLoadAuditLogs: 'Failed to load audit logs.',
    retry: 'Retry',
    noAuditLogsFound: 'No audit logs found',
    auditLogsEmptyDescription: 'Activity will appear here when audit events are recorded.',
    notifications: 'Notifications',
    notificationsSubtitle: 'Stay updated about important RideEasy activity.',
    markAllAsRead: 'Mark all as read',
    allNotifications: 'All',
    emergencyNotifications: 'Emergency',
    rideNotifications: 'Rides',
    driverNotifications: 'Drivers',
    systemNotifications: 'System',
    searchNotifications: 'Search notifications…',
    unableToLoadNotifications: 'Unable to load notifications',
    loadingNotifications: 'Loading notifications…',
    noNotifications: 'No notifications',
    allCaughtUp: 'You’re all caught up.',
    noFilteredNotifications: 'No {filter} notifications are available from the current API.',
    emergencyAlert: 'Emergency Alert',
    highPriority: 'High priority',
    passengerUser: 'Passenger / User',
    location: 'Location',
    city: 'City',
    emergencyTime: 'Emergency time',
    notAvailable: 'Not available',
    acknowledged: 'Acknowledged',
    resolved: 'Resolved',
    viewEmergency: 'View Emergency',
    viewDetails: 'View Details',
    resolveAndCallPolice: 'Resolve & Call Police',
    emergencyDetails: 'Emergency Details',
    emergencyAlertInformation: 'Emergency alert information',
    close: 'Close',
    rideEasyNotification: 'RideEasy Notification',
    newActivityReceived: 'New activity received.',
    newRideArrived: 'New Ride Arrived',
    newRideRequestArrived: 'A new ride request has arrived.',
    driverOnline: 'Driver Online',
    driverOffline: 'Driver Offline',
    driverNowOnline: 'A driver is now online.',
    driverGoneOffline: 'A driver has gone offline.',
    rideAccepted: 'Ride Accepted',
    driverAcceptedRide: 'A driver has accepted a ride.',
    rideStarted: 'Ride Started',
    rideHasStarted: 'A ride has started.',
    rideCompleted: 'Ride Completed',
    rideHasBeenCompleted: 'A ride has been completed.',
    unableToAcknowledgeEmergency: 'Unable to acknowledge emergency',
    emergencyResolvedNoPolicePhone: 'Emergency resolved, but no phone number is available for the nearest police station.',
    unableToResolveEmergency: 'Unable to resolve emergency',
    rolesPermissions: 'Roles & Permissions',
    pricing: 'Pricing',
    settings: 'Settings',
    manageAdminPreferences: 'Manage admin preferences',
    profileSettings: 'Profile Settings',
    adminSettings: 'Admin / Settings',
    manageAdminProfile: 'Manage your administrator profile.',
    fullName: 'Full Name',
    emailAddress: 'Email Address',
    phoneNumber: 'Phone Number',
    adminRole: 'Admin Role',
    administration: 'Administration',
    profileChangesSaved: 'Profile changes saved successfully.',
    cancel: 'Cancel',
    saveChanges: 'Save Changes',

    changePassword: 'Change Password',
    changePasswordSubtitle: 'Update your admin account password.',
    currentPasswordLabel: 'Current Password',
    newPasswordLabel: 'New Password',
    confirmNewPasswordLabel: 'Confirm New Password',
    enterCurrentPassword: 'Enter current password',
    enterNewPassword: 'Enter new password',
    confirmNewPassword: 'Confirm new password',
    fillInAllFields: 'Please fill in all fields.',
    newPasswordMinLength: 'New password must be at least 6 characters.',
    passwordConfirmationMismatch: 'New password and confirmation do not match.',
    passwordChangedSuccessfully: 'Password changed successfully.',
    unableToChangePassword: 'Unable to change password.',
    changingPassword: 'Changing Password…',
    notificationSettings: 'Notification Settings',
    appSettings: 'App Settings',
    appSettingsTitle: 'App Settings',
    managePlatformConfiguration: 'Manage general platform configuration.',
    maintenanceMode: 'Maintenance Mode',
    maintenanceModeDescription: 'Temporarily put the platform into maintenance mode.',
    rideBooking: 'Ride Booking',
    rideBookingDescription: 'Allow users to create new ride bookings.',
    driverRegistration: 'Driver Registration',
    driverRegistrationDescription: 'Allow new drivers to register on the platform.',
    loadingSettings: 'Loading settings…',
    unableToSaveAppSettings: 'Unable to save app settings.',
    savingSettings: 'Saving…',
    saveSettings: 'Save Settings',
    updateAdminProfile: 'Update admin profile',
    updateAdminPassword: 'Update admin password',
    configureNotifications: 'Configure notifications',
    generalAppConfigurations: 'General app configurations',
    logOut: 'Log Out',
    language: 'Language',
    selectPreferredLanguage: 'Select your preferred admin panel language.',
    backToSettings: 'Back to Settings',
    saveLanguage: 'Save Language',
    languagePreferenceSaved: 'Language preference saved successfully.',
    english: 'English',
    hindi: 'Hindi',
    marathi: 'Marathi',
      topDriver: 'Top Driver',
    topDriverSubtitle: 'Driver with the most completed rides',
    pendingActions: 'Pending Actions',
    pendingActionsSubtitle: 'Items that may require your attention',
    driverVerification: 'Driver Verification',
    documentsPending: 'Documents Pending',
    complaintsToReview: 'Complaints to Review',
    failedPayments: 'Failed Payments',
    newDriverRegistered: 'New Driver Registered',
    documentSubmitted: 'Document Submitted',
    paymentReceived: 'Payment Received',
    ridePayment: 'Ride Payment',
    recently: 'Recently',
    justNow: 'just now',
    minAgo: 'min ago',
    hrAgo: 'hr ago',
    dAgo: 'days ago',

    successfullyFinishedTrips: 'Successfully finished trips',
    totalCompleted: 'Total Completed',
    adminVerification: 'Admin Verification',
    all: 'All',
    approve: 'Approve',
    complianceDocumentUploaded: 'Compliance document uploaded successfully.',
    complianceStatusUpdated: 'Compliance status updated successfully.',
    confirmReject: 'Confirm Reject',
    documentExpired: 'Document Expired',
    documentStatus: 'Document Status',
    documentUnreadable: 'Document Unreadable',
    documentVerification: 'Document Verification',
    driverIdMissingApprove: 'Driver ID is missing. Unable to approve verification.',
    driverIdMissingCompliance: 'Driver ID is missing. Unable to update compliance status.',
    driverIdMissingReject: 'Driver ID is missing. Unable to reject verification.',
    driverIdMissingUpload: 'Driver ID is missing. Unable to upload document.',
    email: 'Email',
    enterRejectionReason: 'Enter rejection reason',
    expired: 'Expired',
    expiry: 'Expiry',
    loadingVerificationQueue: 'Loading verification queue…',
    nextPage: 'Next Page',
    noMatchingVerifications: 'No matching verifications found.',
    noVerificationRequests: 'No verification requests found.',
    optional: 'Optional',
    pendingReview: 'Pending Review',
    previousPage: 'Previous Page',
    processing: 'Processing…',
    reUploadRequired: 'Re-upload Required',
    reasonCategory: 'Reason Category',
    refresh: 'Refresh',
    reject: 'Reject',
    rejectReasonMandatory: 'Rejection reason is mandatory.',
    rejected: 'Rejected',
    rejecting: 'Rejecting…',
    rejectionReasonBackend: 'Rejection reason',
    searchVerification: 'Search verification requests',
    selectReasonCategory: 'Select reason category',
    underReview: 'Under Review',
    uploadDate: 'Upload Date',
    verificationApprovedSuccess: 'Verification approved successfully.',
    verificationRejectedSuccess: 'Verification rejected successfully.',
    view: 'View',

    adminPlatformFee: 'Admin Platform Fee',
    assignmentSummary: 'Assignment Summary',
    assignmentTime: 'Assignment Time',
    assignmentTimeline: 'Assignment Timeline',
    bookedFare: 'Booked Fare',
    cancellation: 'Cancellation',
    cancelledBy: 'Cancelled By',
    change: 'Change',
    changeAudit: 'Change Audit',
    chargedAmount: 'Charged Amount',
    clear: 'Clear',
    comment: 'Comment',
    compliments: 'Compliments',
    currentDriver: 'Current Driver',
    currentRideState: 'Current Ride State',
    dateUnavailable: 'Date unavailable',
    delete: 'Delete',
    deleteSelected: 'Delete Selected',
    difference: 'Difference',
    distance: 'Distance',
    driverAccepted: 'Driver Accepted',
    driverArrived: 'Driver Arrived',
    driverGets: 'Driver Gets',
    driverLabel: 'Driver',
    driverRating: 'Driver Rating',
    driverUnavailable: 'Driver unavailable',
    drop: 'Drop',
    eta: 'ETA',
    finalFare: 'Final Fare',
    invalidPin: 'Invalid PIN',
    loadingAuditHistory: 'Loading audit history…',
    loadingRides: 'Loading rides…',
    matchingAttempts: 'Matching Attempts',
    noRidesMatch: 'No rides match the selected filters.',
    noRidesYet: 'No rides yet.',
    none: 'None',
    notAssigned: 'Not assigned',
    notRated: 'Not rated',
    offeredAt: 'Offered At',
    operations: 'Operations',
    passengerRating: 'Passenger Rating',
    paymentBreakdown: 'Payment Breakdown',
    paymentPending: 'Payment Pending',
    pickup: 'Pickup',
    pickupDestination: 'Pickup / Destination',
    pinExpired: 'PIN expired',
    pinVerificationFailed: 'PIN Verification Failed',
    pinVerified: 'PIN Verified',
    ratings: 'Ratings',
    reason: 'Reason',
    refreshTimeline: 'Refresh Timeline',
    refreshing: 'Refreshing…',
    respondedAt: 'Responded At',
    rideCancelled: 'Ride Cancelled',
    rideCreated: 'Ride Created',
    rideDetails: 'Ride Details',
    ridesPageSubtitle: 'Monitor and manage RideEasy rides.',
    searchRides: 'Search rides',
    selected: 'Selected',
    system: 'System',
    tip: 'Tip',
    unassigned: 'Unassigned',
    unnamedUser: 'Unnamed User',
    user: 'User',
    userPaid: 'User Paid',
    when: 'When',

    createdAt: 'Created At',
    customer: 'Customer',
    driverEarning: 'Driver Earning',
    expectedAmount: 'Expected Amount',
    method: 'Method',
    noPaymentTransactions: 'No payment transactions yet.',
    noTransactionsMatch: 'No transactions match the selected filters.',
    paidAmount: 'Paid Amount',
    paymentMethod: 'Payment Method',
    paymentReconciliation: 'Payment Reconciliation',
    paymentReconciliationSubtitle: 'Compare expected and paid amounts, driver settlement status, and reconciliation results.',
    paymentSettlementReconciliationInfo: 'Review payment settlement and reconciliation details.',
    paymentStatus: 'Payment Status',
    paymentType: 'Payment Type',
    reconciliation: 'Reconciliation',
    reconciliationDetails: 'Reconciliation Details',
    rideRoute: 'Ride Route',
    searchPayments: 'Search payments',
    settlement: 'Settlement',
    settlementStatus: 'Settlement Status',
    transaction: 'Transaction',
    transactionId: 'Transaction ID',
    updatedAt: 'Updated At',
    webhookEventId: 'Webhook Event ID',
  },

    servicesPageSubtitle: 'Manage service offerings and pricing',
    serviceList: 'Service List',
    serviceListDescription: 'View and manage all services',
    serviceCategories: 'Service Categories',
    serviceCategoriesDescription: 'Manage service categories',
    pricingSettings: 'Pricing Settings',
    pricingSettingsDescription: 'Configure pricing rules',
    surgeSettings: 'Surge Settings',
    surgeSettingsDescription: 'Manage surge pricing',
    serviceAvailability: 'Service Availability',
    serviceAvailabilityDescription: 'Manage service availability',
    manageRideEasyServices: 'Manage RideEasy services',
    addService: 'Add Service',
    unableLoadServices: 'Unable to load services',
    searchServices: 'Search services...',
    serviceConfiguration: 'Service Configuration',
    editService: 'Edit Service',
    allFareAmountsInINR: 'All fare amounts are in INR.',
    roleAdministration: 'Administration',
    manageAdminRoles: 'Manage admin roles and access permissions.',
    addRole: 'Add Role',
    roleColumn: 'Role',
    descriptionColumn: 'Description',
    usersColumn: 'Users',
    statusColumn: 'Status',
    actionsColumn: 'Actions',
    editRole: 'Edit Role',
    createRole: 'Create Role',
    roleName: 'Role Name',
    roleNameRequired: 'Role name is required.',
    roleNamePlaceholder: 'e.g. Operations',
    roleDescriptionPlaceholder: 'Describe what this role can manage',
    permissions: 'Permissions',
    selectedCount: 'selected',
    uiDemoDataBackendPending: 'UI demo data — backend integration pending.',
    usersCount: 'users',
    fullAccessAllAdminModules: 'Full access to all admin modules.',
    manageDriversRidesLiveOperations: 'Manage drivers, rides and live operations.',
    handleCustomerDriverSupport: 'Handle customer and driver support requests.',
    errorTitle: 'Error',
    confirmLogout: 'Confirm Logout',
    logoutMessage: 'Are you sure you want to logout from the RideEasy Admin Panel?',
    logout: 'Logout',
    backToDrivers: 'Back to drivers',
    unableLoadVehicles: 'Unable to load vehicles',
  hi: {
    userReportUser: 'उपयोगकर्ता',
    loadingUsersReport: 'उपयोगकर्ता रिपोर्ट लोड हो रही है…',
    usersActivitySubtitle: 'उपयोगकर्ता गतिविधि और प्लेटफ़ॉर्म उपयोग का अवलोकन',
    userActivity: 'उपयोगकर्ता गतिविधि',
    userActivitySubtitle: 'उपयोगकर्ता के अनुसार राइड गतिविधि और खर्च',
    noUsersMatch: 'चयनित फ़िल्टर से कोई उपयोगकर्ता मेल नहीं खाता।',
    registered: 'पंजीकृत',
    safetyTitle: 'सुरक्षा',
    safetySubtitle: 'आपातकालीन नियंत्रण और सुरक्षा संचालन',
    emergencyAlerts: 'आपातकालीन अलर्ट',
    emergencyAlertsDescription: 'आपातकालीन अलर्ट देखें और प्रबंधित करें',
    policeStations: 'पुलिस स्टेशन',
    policeStationsDescription: 'नज़दीकी पुलिस स्टेशनों को प्रबंधित करें',
    safetySettings: 'सुरक्षा सेटिंग्स',
    safetySettingsDescription: 'सुरक्षा सुविधाएँ कॉन्फ़िगर करें',
    emergencyContacts: 'आपातकालीन संपर्क',
    emergencyContactsDescription: 'आपातकालीन संपर्क प्रबंधित करें',
    blockedUsersDescription: 'ब्लॉक किए गए उपयोगकर्ताओं की सूची देखें',
    safetyAndEmergency: 'सुरक्षा और आपातकाल',
    safetyControlCenter: 'सुरक्षा नियंत्रण केंद्र',
    monitorEmergencyAlarms: 'आपातकालीन अलार्म की निगरानी करें, यात्री सुरक्षा घटनाओं को प्रबंधित करें और ड्राइवर आवंटन नियमों की समीक्षा करें।',
    safetySystem: 'सुरक्षा प्रणाली',
    emergencyAlarm: 'आपातकालीन अलार्म',
    unknownRider: 'अज्ञात यात्री',
    unknownStatus: 'अज्ञात',
    acknowledge: 'स्वीकार करें',
    resolveCallPolice: 'समाधान करें और पुलिस को कॉल करें',
    noEmergencyAlerts: 'कोई आपातकालीन अलर्ट नहीं',
    noEmergencyAlertsDescription: 'वर्तमान में किसी यात्री सुरक्षा घटना पर ध्यान देने की आवश्यकता नहीं है।',
    availablePoliceContacts: 'आपातकालीन प्रतिक्रिया के लिए उपलब्ध पुलिस संपर्क।',
    noPoliceStationData: 'पुलिस स्टेशन का कोई डेटा उपलब्ध नहीं है।',
    call: 'कॉल करें',
    safetyConfiguration: 'सुरक्षा कॉन्फ़िगरेशन',
    driverAllocationRules: 'ड्राइवर आवंटन नियम',
    ruleActive: 'नियम सक्रिय',
    passenger: 'यात्री',
    femalePassenger: 'महिला यात्री',
    requestsBikeRide: 'बाइक राइड का अनुरोध करती हैं।',
    driverAllocation: 'ड्राइवर आवंटन',
    femaleDriverOnly: 'केवल महिला ड्राइवर',
    eligibleFemaleDriversOnly: 'केवल योग्य महिला ड्राइवर',
    activeAllocationRule: 'सक्रिय आवंटन नियम',
    femalePassengerBikeRule: 'महिला यात्री + बाइक राइड → केवल महिला ड्राइवर।',
    femalePassengerBikeDescription: 'बाइक राइड का अनुरोध करने वाली महिला यात्रियों को केवल योग्य महिला ड्राइवरों को स्वचालित रूप से असाइन किया जाता है।',
    blockedUsersTitle: 'ब्लॉक किए गए उपयोगकर्ता',
    blockedUsersEmpty: 'ब्लॉक किए गए उपयोगकर्ता',
    blockedUsersNotConfigured: 'वर्तमान सुरक्षा डेटा स्रोत में ब्लॉक किए गए उपयोगकर्ता प्रबंधन कॉन्फ़िगर नहीं है।',
    rideEasySupport: 'RideEasy सहायता',
    rideEasySupportDescription: 'आपातकालीन और ग्राहक सहायता संपर्क प्रबंधित करें।',
    loadingRideEasySupport: 'RideEasy सहायता लोड हो रही है...',
    supportStatus: 'सहायता स्थिति',
    supportActive: 'RideEasy सहायता वर्तमान में सक्रिय है।',
    supportInactive: 'RideEasy सहायता वर्तमान में निष्क्रिय है।',
    name: 'नाम',
    phone: 'फ़ोन',
    description: 'विवरण',
    supportChangesUpdate: 'परिवर्तन मौजूदा RideEasy सहायता रिकॉर्ड को अपडेट करेंगे।',
    supportRecordCreated: 'एक RideEasy सहायता रिकॉर्ड बनाया जाएगा।',
    saving: 'सहेज रहे हैं...',
    saveSupport: 'सहायता सहेजें',
    failedLoadSupport: 'RideEasy सहायता लोड करने में विफल।',
    supportUpdatedSuccessfully: 'RideEasy सहायता सफलतापूर्वक अपडेट की गई।',
    failedUpdateSupport: 'RideEasy सहायता अपडेट करने में विफल।',

    helpSupport: 'मदद और सहायता',
    reportsPageTitle: 'रिपोर्ट',
    reportsPageSubtitle: 'प्लेटफ़ॉर्म एनालिटिक्स और रिपोर्ट देखें',

    loadingDriversReport: 'ड्राइवर रिपोर्ट लोड हो रही है…',
    driversActivitySubtitle: 'ड्राइवर गतिविधि और प्रदर्शन का अवलोकन',
    driverPerformance: 'ड्राइवर प्रदर्शन',
    driverPerformanceSubtitle: 'ड्राइवर गतिविधि, पूरी हुई राइड्स और कमाई',
    noDriverRecords: 'ड्राइवर रिकॉर्ड नहीं मिले।',
    approval: 'मंजूरी',
    earnings: 'कमाई',    loadingBookingsReport: 'बुकिंग रिपोर्ट लोड हो रही है…',
    bookingsActivitySubtitle: 'बुकिंग गतिविधि और राइड स्थिति का अवलोकन',
    bookingDetails: 'बुकिंग विवरण',
    bookingDetailsSubtitle: 'राइड, यात्री, ड्राइवर और किराए की जानकारी',
    noBookingsFound: 'कोई बुकिंग नहीं मिली',
    loadingEarningsReport: 'अर्निंग्स रिपोर्ट लोड हो रही है…',
    fromCompletedRides: 'पूरी हुई राइड्स से',
    recordedCaptainEarnings: 'रिकॉर्ड की गई कैप्टन कमाई',
    recordedPlatformFees: 'रिकॉर्ड की गई प्लेटफ़ॉर्म फीस',
    appliedToCompletedRides: 'पूरी हुई राइड्स पर लागू',
    completedRidesIncluded: 'इस रिपोर्ट में शामिल पूरी हुई राइड्स',
    noCompletedRideEarnings: 'पूरी हुई राइड्स की कोई कमाई नहीं मिली',
    tryAnotherDateRange: 'कोई दूसरी तारीख सीमा आज़माएँ।',
    earningsReport: 'कमाई रिपोर्ट',
    earningsReportDescription: 'कमाई का विश्लेषण देखें',
    bookingsReport: 'बुकिंग रिपोर्ट',
    bookingsReportDescription: 'बुकिंग का विश्लेषण देखें',
    driversReport: 'ड्राइवर रिपोर्ट',
    driversReportDescription: 'ड्राइवर प्रदर्शन देखें',
    usersReport: 'उपयोगकर्ता रिपोर्ट',
    usersReportDescription: 'उपयोगकर्ता विश्लेषण देखें',
    downloadReports: 'रिपोर्ट डाउनलोड करें',
    downloadReportsDescription: 'CSV में डेटा डाउनलोड करें',
    backToReports: 'रिपोर्ट पर वापस जाएं',
    revenueAndEarningsOverview: 'पूरी हुई राइड से राजस्व और कमाई का अवलोकन',
    allTime: 'सभी समय',
    last7Days: 'पिछले 7 दिन',
    last30Days: 'पिछले 30 दिन',
    last90Days: 'पिछले 90 दिन',
    discounts: 'छूट',
    rideEarnings: 'राइड की कमाई',
    fare: 'किराया',
    ongoing: 'जारी',
    cancelled: 'रद्द',
    bookingValue: 'बुकिंग मूल्य',
    allStatuses: 'सभी स्थितियां',
    started: 'शुरू हुई',
    accepted: 'स्वीकृत',
    pending: 'लंबित',
    ride: 'राइड',
    route: 'मार्ग',
    online: 'ऑनलाइन',
    offline: 'ऑफलाइन',
    busy: 'व्यस्त',
    onlineDrivers: 'ऑनलाइन ड्राइवर',
    offlineDrivers: 'ऑफलाइन ड्राइवर',
    approvedDrivers: 'स्वीकृत ड्राइवर',
    searchDriver: 'ड्राइवर, फ़ोन, वाहन या शहर खोजें...',
    approved: 'स्वीकृत',
    usersReportSearch: 'उपयोगकर्ता, ईमेल, फ़ोन या शहर खोजें...',
    active: 'सक्रिय',
    activeUsers: 'सक्रिय उपयोगकर्ता',
    blockedUsers: 'ब्लॉक किए गए उपयोगकर्ता',
    totalRides: 'कुल राइड',
    userSpending: 'उपयोगकर्ता खर्च',
    spending: 'खर्च',
    cancelledRidesInSelectedPeriod: 'चयनित अवधि में रद्द हुई राइड',

    helpSupportSubtitle: 'मदद और सहायता प्राप्त करें',
    needHelp: 'मदद चाहिए?',
    needHelpText: 'यदि आपको RideEasy Admin Panel में कोई समस्या आ रही है, तो सहायता के लिए सपोर्ट टीम से संपर्क करें।',
    adminSupport: 'एडमिन सहायता',
    adminSupportText: 'अकाउंट, डैशबोर्ड, ड्राइवर, बुकिंग या भुगतान से संबंधित समस्याओं के लिए RideEasy प्रशासन टीम से संपर्क करें।',
    contactSupport: 'सहायता से संपर्क करें',
    contactSupportText: 'सहायता संपर्क विवरण यहां उपलब्ध होंगे।',
    supportCasesSubtitle: 'उपयोगकर्ता और ड्राइवर सहायता मामलों की समीक्षा और जांच करें',
    supportCases: 'सहायता मामले',
    caseShown: 'मामला दिखाया गया',
    casesShown: 'मामले दिखाए गए',
    searchSupportCases: 'मामला, राइड, उपयोगकर्ता या श्रेणी खोजें...',
    supportAll: 'सभी',
    supportUser: 'उपयोगकर्ता',
    supportDriver: 'ड्राइवर',
    supportOpen: 'खुला',
    supportInReview: 'समीक्षा में',
    supportEscalated: 'एस्केलेटेड',
    supportResolved: 'समाधान किया गया',
    loadingSupportCases: 'सहायता मामले लोड हो रहे हैं...',
    unableLoadSupportCases: 'सहायता मामले लोड नहीं हो सके',
    noSupportCases: 'कोई सहायता मामला नहीं मिला',
    tryAnotherSearchFilter: 'कोई दूसरा खोज शब्द या फ़िल्टर आज़माएं।',
    caseLabel: 'मामला',
    closeCaseDetails: 'मामले का विवरण बंद करें',
    priorityLabel: 'प्राथमिकता',
    subject: 'विषय',
    userDriver: 'उपयोगकर्ता / ड्राइवर',
    rideIdLabel: 'राइड आईडी',
    rideStatus: 'राइड स्थिति',
    cancellationReason: 'रद्द करने का कारण',
    assignedOwner: 'असाइन किया गया व्यक्ति',
    investigationContext: 'जांच संदर्भ',
    statusHistory: 'स्थिति इतिहास',
    caseCreated: 'मामला बनाया गया',
    currentStatus: 'वर्तमान स्थिति',
    statusTransitionUnavailable: 'स्थिति परिवर्तन का समय उपलब्ध नहीं है',
    supportHigh: 'उच्च',
    supportMedium: 'मध्यम',
    supportLow: 'कम',
    supportPriority: 'प्राथमिकता',



    invoicesPageTitle: 'इनवॉइस',
    invoicesPageSubtitle: 'राइड इनवॉइस, किराया कुल और संबंधित भुगतान जानकारी देखें।',
    platformRevenue: 'प्लेटफ़ॉर्म राजस्व',
    totalPaidAmount: 'कुल भुगतान राशि',
    platformCommission: 'प्लेटफ़ॉर्म कमीशन',
    platformFeeEarned: 'अर्जित प्लेटफ़ॉर्म शुल्क',
    driverShare: 'ड्राइवर हिस्सा',
    driverEarnings: 'ड्राइवर की कमाई',
    pendingPayouts: 'लंबित भुगतान',
    driverSettlementsPending: 'ड्राइवर सेटलमेंट लंबित',
    invoiceDetail: 'इनवॉइस विवरण',
    invoiceInformation: 'इनवॉइस जानकारी',
    paymentLinkage: 'भुगतान लिंक जानकारी',
    fareAndTotal: 'किराया और कुल',
    authoritativeInvoiceTotal: 'मान्य इनवॉइस कुल',
    invoiceList: 'इनवॉइस सूची',
    invoiceTotalSource: 'इनवॉइस कुल मान्य राइड राशि से लिया गया है।',
    searchInvoice: 'इनवॉइस, राइड, ग्राहक, राशि खोजें…',
    loadingInvoices: 'इनवॉइस लोड हो रहे हैं…',
    noRideInvoices: 'कोई राइड इनवॉइस उपलब्ध नहीं है।',
    noInvoicesMatch: 'आपकी खोज से कोई इनवॉइस मेल नहीं खाता।',
    invoice: 'इनवॉइस',
    paymentId: 'भुगतान आईडी',
    fareConfigurationTitle: 'किराया कॉन्फ़िगरेशन',
    configureVersionedFares: 'राइड श्रेणी और शहर / ज़ोन के अनुसार नियंत्रित प्रभावी अवधि के साथ संस्करणित किराए कॉन्फ़िगर करें।',
    fareVersions: 'किराया संस्करण',
    editDraftFare: 'ड्राफ्ट किराया संपादित करें',
    createFareConfiguration: 'किराया कॉन्फ़िगरेशन बनाएं',
    activeHistoricalVersions: 'सक्रिय और पुराने संस्करणों को चुपचाप बदला नहीं जा सकता।',
    cancelEdit: 'संपादन रद्द करें',
    rideTypeLabel: 'राइड प्रकार',
    cityZoneLabel: 'शहर / ज़ोन',
    distanceRate: 'दूरी दर / किमी',
    timeRate: 'समय दर / मिनट',
    minimumFare: 'न्यूनतम किराया',
    fees: 'शुल्क',
    registrationFee: 'पंजीकरण शुल्क',
    minimumWalletBalance: 'न्यूनतम वॉलेट बैलेंस',
    taxPercentage: 'टैक्स (%)',
    effectiveFrom: 'प्रभावी समय से',
    effectiveTo: 'प्रभावी समय तक',
    saveAsDraft: 'ड्राफ्ट के रूप में सेव करें',
    activationDescription: 'एक्टिवेशन एक अलग पुष्टि की गई कार्रवाई है और ओवरलैपिंग सक्रिय अवधियों के विरुद्ध सत्यापित की जाती है।',
    calculating: 'गणना की जा रही है…',
    previewFare: 'किराए का पूर्वावलोकन',
    updateDraft: 'ड्राफ्ट अपडेट करें',
    createDraft: 'ड्राफ्ट बनाएं',
    farePreview: 'किराया पूर्वावलोकन',
    fareConfigurationList: 'किराया कॉन्फ़िगरेशन सूची',
    fareConfigurationListSubtitle: 'राइड प्रकार, शहर / ज़ोन, संस्करण, स्थिति और प्रभावी अवधि।',
    version: 'संस्करण',
    noFareConfigurations: 'कोई किराया कॉन्फ़िगरेशन नहीं मिला।',
    edit: 'संपादित करें',
    activate: 'सक्रिय करें',
    deactivate: 'निष्क्रिय करें',
    history: 'इतिहास',
    baseFare: 'मूल किराया',
    discount: 'छूट',
    paymentAmount: 'भुगतान राशि',
    total: 'कुल',

    dashboard: 'डैशबोर्ड',
    users: 'उपयोगकर्ता',
    drivers: 'ड्राइवर',
    vehicles: 'वाहन',
    manageRegisteredVehicles: 'पंजीकृत वाहनों और सत्यापन स्थिति को प्रबंधित करें',
    allVehicles: 'सभी वाहन',
    searchVehicles: 'वाहन नंबर, प्रकार, मॉडल या ड्राइवर खोजें...',
    vehicleStatusLabel: 'स्थिति',
    noVehiclesFound: 'कोई वाहन नहीं मिला',
    noVehiclesMatch: 'कोई वाहन आपकी वर्तमान खोज या फ़िल्टर से मेल नहीं खाता।',
    loadingVehicles: 'वाहन लोड हो रहे हैं...',
    vehicleDetails: 'वाहन विवरण',
    unnamedDriver: 'अनाम ड्राइवर',
    vehicleModel: 'वाहन मॉडल',
    driverEmail: 'ड्राइवर ईमेल',
    driverPhone: 'ड्राइवर फोन',
    rcStatus: 'आरसी स्थिति',
    insuranceStatus: 'बीमा स्थिति',
    registrationDate: 'पंजीकरण तिथि',
    vehicleStatus: 'वाहन स्थिति',
    pendingVerification: 'सत्यापन लंबित',
    vehicleColumn: 'वाहन',
    modelColumn: 'मॉडल',
    driverColumn: 'ड्राइवर',
    vehicleRecordsSource: 'वाहन रिकॉर्ड पंजीकृत ड्राइवरों से प्राप्त किए जाते हैं।',

    verification: 'सत्यापन',
    verificationQueue: 'सत्यापन कतार',
    valid: 'मान्य',
    expiringSoon: 'जल्द समाप्त होने वाला',
    reviewDriverVerificationInfo: 'ड्राइवर सत्यापन जानकारी की समीक्षा करें',
    verificationDocuments: 'सत्यापन दस्तावेज़',
    documentReview: 'दस्तावेज़ समीक्षा',
    statusLabel: 'स्थिति',
    versionLabel: 'संस्करण',
    documentInformation: 'दस्तावेज़ जानकारी',
    noExtractedDocumentInformation: 'कोई निकाली गई दस्तावेज़ जानकारी नहीं है',
    apiDidNotProvideDocumentFields: 'API ने अतिरिक्त दस्तावेज़ फ़ील्ड उपलब्ध नहीं कराए।',
    documentPreview: 'दस्तावेज़ पूर्वावलोकन',
    openDocument: 'खोलें',
    loadingDocumentPreview: 'दस्तावेज़ पूर्वावलोकन लोड हो रहा है...',
    previewUnavailable: 'पूर्वावलोकन उपलब्ध नहीं है',
    authorizedDocumentPreviewUnavailable: 'अधिकृत दस्तावेज़ पूर्वावलोकन लोड नहीं किया जा सका।',
    back: 'वापस',
    unableToLoadVerificationQueue: 'सत्यापन कतार लोड नहीं की जा सकी',
    rejectVerification: 'सत्यापन अस्वीकार करें',
    unableToLoadDocumentPreview: 'दस्तावेज़ पूर्वावलोकन लोड नहीं किया जा सका',
    viewDocuments: 'दस्तावेज़ देखें',
    noDocumentsReturned: 'ड्राइवर API ने इस ड्राइवर के लिए कोई दस्तावेज़ रिकॉर्ड नहीं लौटाया।',
    noDocumentsAvailable: 'कोई दस्तावेज़ उपलब्ध नहीं है',
    uploadDocument: 'दस्तावेज़ अपलोड करें',
    notSubmitted: 'जमा नहीं किया गया',
    submitted: 'जमा किया गया',
    psychologicalAssessment: 'मनोवैज्ञानिक मूल्यांकन',
    eyeExamination: 'नेत्र परीक्षण',
    medicalFitness: 'चिकित्सकीय फिटनेस',
    policeVerification: 'पुलिस सत्यापन',
    reviewCompliance: 'ड्राइवर की अनिवार्य अनुपालन आवश्यकताओं की समीक्षा करें।',
    captainCompliance: 'कैप्टन अनुपालन',
    rejectionReason: 'अस्वीकृति का कारण',
    subscriptionExpiry: 'सदस्यता समाप्ति',
    overallStatus: 'कुल स्थिति',
    lastUpdated: 'अंतिम अपडेट',
    licence: 'लाइसेंस',
    vehicleNumber: 'वाहन नंबर',
    vehicleType: 'वाहन प्रकार',
    driverDetails: 'ड्राइवर विवरण',
    reviewVerificationRequests: 'ड्राइवर सत्यापन अनुरोधों और जमा किए गए दस्तावेज़ों की समीक्षा करें।',
    rides: 'राइड्स',
    liveOperations: 'लाइव ऑपरेशंस',
    liveOpsPageSubtitle: 'ड्राइवर की उपलब्धता और सक्रिय राइड की स्थिति देखें।',
    liveOpsUpdatesConnected: 'लाइव अपडेट कनेक्ट हैं',
    liveOpsReconnecting: 'लाइव अपडेट फिर से कनेक्ट हो रहे हैं…',
    liveOpsUpdatesDisabled: 'लाइव अपडेट बंद हैं',
    liveOpsUpdatesDisconnected: 'लाइव अपडेट डिस्कनेक्ट हैं',
    liveOpsAvailableDrivers: 'उपलब्ध ड्राइवर',
    liveOpsDriversOnActiveRides: 'सक्रिय राइड पर ड्राइवर',
    liveOpsCurrentlyUnavailable: 'वर्तमान में अनुपलब्ध',
    liveOpsLiveMap: 'लाइव मैप',
    liveOpsLive: 'लाइव',
    liveOpsStale: 'पुराना',
    liveOpsDriverActiveLocations: 'ड्राइवर और सक्रिय राइड के स्थान',
    liveOpsLoadingMap: 'लाइव मैप लोड हो रहा है...',
    liveOpsFetchingLocations: 'ड्राइवर और सक्रिय राइड के स्थान प्राप्त किए जा रहे हैं।',
    liveOpsUnableLoadMap: 'लाइव मैप लोड नहीं हो सका',
    liveOpsLocationsCouldNotLoad: 'ड्राइवर और सक्रिय राइड के स्थान लोड नहीं हो सके।',
    liveOpsNoLocations: 'कोई लाइव स्थान उपलब्ध नहीं है',
    liveOpsLocationsAppearHere: 'ड्राइवर और सक्रिय राइड के स्थान यहां दिखाई देंगे।',
    liveOpsDriverStatus: 'ड्राइवर स्थिति',
    liveOpsDriver: 'ड्राइवर',
    liveOpsDrivers: 'ड्राइवर',
    liveOpsShown: 'दिखाए गए',
    liveOpsSearchDriver: 'ड्राइवर खोजें...',
    liveOpsAllStatuses: 'सभी स्थितियां',
    liveOpsLoadingStatus: 'ड्राइवर की स्थिति लोड हो रही है...',
    liveOpsTryAgain: 'फिर से प्रयास करें',
    liveOpsNoDrivers: 'कोई ड्राइवर नहीं मिला',
    liveOpsChangeFilter: 'अपनी खोज या स्थिति फ़िल्टर बदलकर देखें।',
    liveOpsUnnamedDriver: 'अनाम ड्राइवर',
    liveOpsNoContact: 'कोई संपर्क नहीं',
    liveOpsVehicle: 'वाहन',
    liveOpsStatus: 'स्थिति',
    liveOpsOnline: 'ऑनलाइन',
    liveOpsBusy: 'व्यस्त',
    liveOpsOffline: 'ऑफलाइन',
    liveOpsUnableLoadDrivers: 'ड्राइवर की लाइव स्थिति लोड नहीं हो सकी।',

    couponPageTitle: 'कूपन',
    couponPageSubtitle: 'प्रमोशनल कूपन बनाएं और प्रबंधित करें।',
    couponCreate: 'कूपन बनाएं',
    couponSearch: 'कूपन कोड खोजें...',
    couponAllStatus: 'सभी स्थिति',
    couponActive: 'सक्रिय',
    couponExpired: 'समाप्त',
    couponCode: 'कूपन कोड',
    couponDiscount: 'छूट',
    couponMinRide: 'न्यूनतम राइड',
    couponValidity: 'वैधता',
    couponUsage: 'उपयोग',
    couponStatus: 'स्थिति',
    couponActions: 'कार्रवाइयां',
    couponEdit: 'संपादित करें',
    couponDelete: 'हटाएं',
    couponNoCoupons: 'कोई कूपन नहीं मिला।',
    couponEditTitle: 'कूपन संपादित करें',
    couponCreateTitle: 'कूपन बनाएं',
    couponUpdateDetails: 'कूपन का विवरण अपडेट करें।',
    couponCreateForRiders: 'राइडर्स के लिए प्रमोशनल कूपन बनाएं।',
    couponCodeRequired: 'कूपन कोड *',
    couponDiscountTypeRequired: 'छूट का प्रकार *',
    couponPercentage: 'प्रतिशत (%)',
    couponFixedAmount: 'निश्चित राशि (₹)',
    couponDiscountValueRequired: 'छूट राशि *',
    couponMinimumRideRequired: 'न्यूनतम राइड राशि *',
    couponMaximumDiscount: 'अधिकतम छूट',
    couponValidFromRequired: 'मान्य प्रारंभ *',
    couponValidUntilRequired: 'मान्य समाप्ति *',
    couponUsageLimitRequired: 'उपयोग सीमा *',
    couponCancel: 'रद्द करें',
    couponUpdate: 'कूपन अपडेट करें',
    couponSave: 'कूपन सेव करें',
    couponFillRequired: 'कृपया सभी आवश्यक फ़ील्ड भरें।',
    couponLoadFailed: 'कूपन लोड नहीं हो सके।',
    couponSaveFailed: 'कूपन सेव नहीं हो सका।',
    couponDeleteFailed: 'कूपन हटाया नहीं जा सका।',
    couponDeleteConfirm: 'कूपन हटाएं',
    couponExample: 'उदा.',

    finance: 'वित्त',
    coupons: 'कूपन',
    payments: 'भुगतान',
    sos: 'SOS',
    support: 'सहायता',
    reports: 'रिपोर्ट्स',
    auditLogs: 'ऑडिट लॉग्स',
    auditLogsSubtitle: 'एडमिन और सिस्टम गतिविधियों की समीक्षा करें।',
    allActors: 'सभी एक्टर्स',
    actorType: 'एक्टर प्रकार',
    allTargets: 'सभी लक्ष्य',
    target: 'लक्ष्य',
    timestamp: 'समय',
    loadingAuditLogs: 'ऑडिट लॉग्स लोड हो रहे हैं…',
    failedToLoadAuditLogs: 'ऑडिट लॉग्स लोड करने में असमर्थ।',
    retry: 'पुनः प्रयास करें',
    noAuditLogsFound: 'कोई ऑडिट लॉग नहीं मिला',
    auditLogsEmptyDescription: 'ऑडिट इवेंट रिकॉर्ड होने पर गतिविधि यहां दिखाई देगी।',
    notifications: 'सूचनाएं',
    notificationsSubtitle: 'महत्वपूर्ण RideEasy गतिविधियों की जानकारी प्राप्त करें।',
    markAllAsRead: 'सभी को पढ़ा हुआ चिन्हित करें',
    allNotifications: 'सभी',
    emergencyNotifications: 'आपातकाल',
    rideNotifications: 'राइड्स',
    driverNotifications: 'ड्राइवर',
    systemNotifications: 'सिस्टम',
    searchNotifications: 'सूचनाएं खोजें…',
    unableToLoadNotifications: 'सूचनाएं लोड करने में असमर्थ',
    loadingNotifications: 'सूचनाएं लोड हो रही हैं…',
    noNotifications: 'कोई सूचनाएं नहीं',
    allCaughtUp: 'आप सभी सूचनाओं से अपडेट हैं।',
    noFilteredNotifications: 'वर्तमान API से कोई {filter} सूचनाएं उपलब्ध नहीं हैं।',
    emergencyAlert: 'आपातकालीन अलर्ट',
    highPriority: 'उच्च प्राथमिकता',
    passengerUser: 'यात्री / उपयोगकर्ता',
    location: 'स्थान',
    city: 'शहर',
    emergencyTime: 'आपातकालीन समय',
    notAvailable: 'उपलब्ध नहीं',
    acknowledged: 'स्वीकार किया गया',
    resolved: 'समाधान किया गया',
    viewEmergency: 'आपातकाल देखें',
    viewDetails: 'विवरण देखें',
    resolveAndCallPolice: 'समाधान करें और पुलिस को कॉल करें',
    emergencyDetails: 'आपातकालीन विवरण',
    emergencyAlertInformation: 'आपातकालीन अलर्ट की जानकारी',
    close: 'बंद करें',
    rideEasyNotification: 'RideEasy सूचना',
    newActivityReceived: 'नई गतिविधि प्राप्त हुई।',
    newRideArrived: 'नई राइड प्राप्त हुई',
    newRideRequestArrived: 'नई राइड का अनुरोध प्राप्त हुआ है।',
    driverOnline: 'ड्राइवर ऑनलाइन',
    driverOffline: 'ड्राइवर ऑफलाइन',
    driverNowOnline: 'एक ड्राइवर अब ऑनलाइन है।',
    driverGoneOffline: 'एक ड्राइवर ऑफलाइन हो गया है।',
    rideAccepted: 'राइड स्वीकार की गई',
    driverAcceptedRide: 'एक ड्राइवर ने राइड स्वीकार कर ली है।',
    rideStarted: 'राइड शुरू हुई',
    rideHasStarted: 'एक राइड शुरू हो गई है।',
    rideCompleted: 'राइड पूरी हुई',
    rideHasBeenCompleted: 'एक राइड पूरी हो गई है।',
    unableToAcknowledgeEmergency: 'आपातकाल स्वीकार करने में असमर्थ',
    emergencyResolvedNoPolicePhone: 'आपातकाल का समाधान हो गया, लेकिन निकटतम पुलिस स्टेशन का फोन नंबर उपलब्ध नहीं है।',
    unableToResolveEmergency: 'आपातकाल का समाधान करने में असमर्थ',
    rolesPermissions: 'भूमिकाएं और अनुमतियां',
    pricing: 'मूल्य निर्धारण',
    settings: 'सेटिंग्स',
    manageAdminPreferences: 'एडमिन प्राथमिकताएं प्रबंधित करें',
    profileSettings: 'प्रोफ़ाइल सेटिंग्स',
    adminSettings: 'एडमिन / सेटिंग्स',
    manageAdminProfile: 'अपनी एडमिन प्रोफ़ाइल प्रबंधित करें।',
    fullName: 'पूरा नाम',
    emailAddress: 'ईमेल पता',
    phoneNumber: 'फ़ोन नंबर',
    adminRole: 'एडमिन भूमिका',
    administration: 'प्रशासन',
    profileChangesSaved: 'प्रोफ़ाइल में बदलाव सफलतापूर्वक सहेजे गए।',
    cancel: 'रद्द करें',
    saveChanges: 'बदलाव सहेजें',

    changePassword: 'पासवर्ड बदलें',
    changePasswordSubtitle: 'अपना एडमिन अकाउंट पासवर्ड अपडेट करें।',
    currentPasswordLabel: 'वर्तमान पासवर्ड',
    newPasswordLabel: 'नया पासवर्ड',
    confirmNewPasswordLabel: 'नए पासवर्ड की पुष्टि करें',
    enterCurrentPassword: 'वर्तमान पासवर्ड दर्ज करें',
    enterNewPassword: 'नया पासवर्ड दर्ज करें',
    confirmNewPassword: 'नया पासवर्ड फिर से दर्ज करें',
    fillInAllFields: 'कृपया सभी फ़ील्ड भरें।',
    newPasswordMinLength: 'नया पासवर्ड कम से कम 6 अक्षरों का होना चाहिए।',
    passwordConfirmationMismatch: 'नया पासवर्ड और पुष्टि मेल नहीं खाते।',
    passwordChangedSuccessfully: 'पासवर्ड सफलतापूर्वक बदल दिया गया।',
    unableToChangePassword: 'पासवर्ड बदलने में असमर्थ।',
    changingPassword: 'पासवर्ड बदला जा रहा है…',
    notificationSettings: 'सूचना सेटिंग्स',
    appSettings: 'ऐप सेटिंग्स',
    appSettingsTitle: 'ऐप सेटिंग्स',
    managePlatformConfiguration: 'सामान्य प्लेटफ़ॉर्म कॉन्फ़िगरेशन प्रबंधित करें।',
    maintenanceMode: 'मेंटेनेंस मोड',
    maintenanceModeDescription: 'प्लेटफ़ॉर्म को अस्थायी रूप से मेंटेनेंस मोड में रखें।',
    rideBooking: 'राइड बुकिंग',
    rideBookingDescription: 'उपयोगकर्ताओं को नई राइड बुकिंग बनाने की अनुमति दें।',
    driverRegistration: 'ड्राइवर पंजीकरण',
    driverRegistrationDescription: 'नए ड्राइवरों को प्लेटफ़ॉर्म पर पंजीकरण करने की अनुमति दें।',
    loadingSettings: 'सेटिंग्स लोड हो रही हैं…',
    unableToSaveAppSettings: 'ऐप सेटिंग्स सेव करने में असमर्थ।',
    savingSettings: 'सेव किया जा रहा है…',
    saveSettings: 'सेटिंग्स सेव करें',
    updateAdminProfile: 'एडमिन प्रोफ़ाइल अपडेट करें',
    updateAdminPassword: 'एडमिन पासवर्ड अपडेट करें',
    configureNotifications: 'सूचनाएं कॉन्फ़िगर करें',
    generalAppConfigurations: 'सामान्य ऐप कॉन्फ़िगरेशन',
    logOut: 'लॉग आउट',

    language: 'भाषा',
    selectPreferredLanguage: 'अपनी पसंदीदा एडमिन पैनल भाषा चुनें।',
    backToSettings: 'सेटिंग्स पर वापस जाएं',
    saveLanguage: 'भाषा सेव करें',
    languagePreferenceSaved: 'भाषा की पसंद सफलतापूर्वक सेव हो गई।',
    english: 'अंग्रेज़ी',
    hindi: 'हिंदी',
    marathi: 'मराठी',
    switchToLightMode: 'लाइट मोड पर स्विच करें',
    switchToDarkMode: 'डार्क मोड पर स्विच करें',
    lightMode: 'लाइट मोड',
    darkMode: 'डार्क मोड',
    refresh: 'रिफ्रेश',
    overviewPlatform: 'आपके प्लेटफ़ॉर्म का अवलोकन',
    totalUsers: 'कुल उपयोगकर्ता',
    totalDrivers: 'कुल ड्राइवर',
    totalBookings: 'कुल बुकिंग',
    totalRevenue: 'कुल राजस्व',
    completedRides: 'पूरी हुई राइड्स',
    successfullyFinishedTrips: 'सफलतापूर्वक पूरी हुई यात्राएं',
    totalCompleted: 'कुल पूर्ण',
    topDriver: 'शीर्ष ड्राइवर',
    topDriverSubtitle: 'सबसे अधिक पूरी हुई राइड्स वाला ड्राइवर',
    noDriverData: 'ड्राइवर का डेटा उपलब्ध नहीं',
    completedRidesLabel: 'पूरी हुई राइड्स',
    pendingActions: 'लंबित कार्य',
    pendingActionsSubtitle: 'जिन आइटम पर आपके ध्यान की आवश्यकता हो सकती है',
    driverVerification: 'ड्राइवर सत्यापन',
    documentsPending: 'दस्तावेज़ लंबित',
    complaintsToReview: 'समीक्षा के लिए शिकायतें',
    failedPayments: 'असफल भुगतान',
    reviewNow: 'अभी समीक्षा करें',
    recentActivity: 'हाल की गतिविधि',
    newDriverRegistered: 'नया ड्राइवर पंजीकृत',
    documentSubmitted: 'दस्तावेज़ जमा किया गया',
    paymentReceived: 'भुगतान प्राप्त हुआ',
    live: 'लाइव',
    loadingDashboard: 'डैशबोर्ड लोड हो रहा है...',
    unableToLoadDashboard: 'डैशबोर्ड लोड नहीं हो सका',
    tryAgain: 'पुनः प्रयास करें',
    recently: 'हाल ही में',
    justNow: 'अभी',
    minAgo: 'मिनट पहले',
    hrAgo: 'घंटे पहले',
    dAgo: 'दिन पहले',
    rating: 'रेटिंग',
    driverFallback: 'ड्राइवर',
    driverDocuments: 'ड्राइवर के दस्तावेज़',
    completedRideFallback: 'पूरी हुई राइड',
    ridePayment: 'राइड भुगतान',
    ridesPageSubtitle: 'सभी राइड्स का प्रबंधन और निगरानी करें।',
    paymentReconciliation: 'भुगतान मिलान',
    paymentReconciliationSubtitle: 'अपेक्षित और भुगतान की गई राशि, ड्राइवर सेटलमेंट स्थिति और मिलान परिणामों की तुलना करें।',
    expectedAmount: 'अपेक्षित राशि',
    paidAmount: 'भुगतान की गई राशि',
    paymentStatus: 'भुगतान स्थिति',
    reconciliation: 'मिलान',
    settlementStatus: 'सेटलमेंट स्थिति',
    driverEarning: 'ड्राइवर की कमाई',
    platformFee: 'प्लेटफ़ॉर्म शुल्क',
    reconciliationDetails: 'मिलान विवरण',
    paymentSettlementReconciliationInfo: 'भुगतान, सेटलमेंट और मिलान की जानकारी',
    transactionId: 'लेन-देन आईडी',
    paymentMethod: 'भुगतान विधि',
    paymentType: 'भुगतान प्रकार',
    providerReference: 'प्रदाता संदर्भ',
    webhookEventId: 'वेबहुक इवेंट आईडी',
    createdAt: 'बनाया गया',
    updatedAt: 'अपडेट किया गया',
    all: 'सभी',
    date: 'तारीख',
    driverLabel: 'ड्राइवर',
    allDrivers: 'सभी ड्राइवर',
    unnamedUser: 'बिना नाम का उपयोगकर्ता',
    searchRides: 'शहर, रूट, यात्री, ड्राइवर, आईडी खोजें…',
    deleteSelected: 'चयनित हटाएँ',
    loadingRides: 'राइड्स लोड हो रही हैं…',
    dateUnavailable: 'तारीख उपलब्ध नहीं',
    pickup: 'पिकअप',
    drop: 'ड्रॉप',
    driver: 'ड्राइवर',
    unassigned: 'असाइन नहीं किया गया',
    vehicle: 'वाहन',
    distance: 'दूरी',
    bookedFare: 'बुक किया गया किराया',
    finalFare: 'अंतिम किराया',
    paymentPending: 'भुगतान लंबित',
    difference: 'अंतर',
    payment: 'भुगतान',
    when: 'समय',
    rider: 'यात्री',
    pickupDestination: 'पिकअप → गंतव्य',
    completed: 'पूरी हुई',
    action: 'कार्रवाई',
    noRidesYet: 'अभी डेटाबेस में कोई राइड नहीं है। Status में All चुनें या बैकएंड कनेक्शन जाँचें।',
    noRidesMatch: 'आपकी खोज या फ़िल्टर से कोई राइड मेल नहीं खाती।',
    rideDetails: 'राइड विवरण',
    rideId: 'राइड आईडी',
    chargedAmount: 'चार्ज की गई राशि',
    created: 'बनाई गई',
    paymentBreakdown: 'भुगतान विवरण',
    userPaid: 'उपयोगकर्ता ने भुगतान किया',
    driverGets: 'ड्राइवर को मिलता है',
    adminPlatformFee: 'एडमिन / प्लेटफ़ॉर्म शुल्क',
    assignmentSummary: 'असाइनमेंट सारांश',
    currentDriver: 'वर्तमान ड्राइवर',
    currentRideState: 'वर्तमान राइड स्थिति',
    assignmentTime: 'असाइनमेंट समय',
    notAssigned: 'असाइन नहीं किया गया',
    eta: 'अनुमानित समय',
    matchingAttempts: 'मैचिंग प्रयास',
    driverUnavailable: 'ड्राइवर उपलब्ध नहीं',
    offeredAt: 'ऑफ़र किया गया',
    respondedAt: 'प्रतिक्रिया दी गई',
    assignmentTimeline: 'असाइनमेंट टाइमलाइन',
    refreshing: 'रिफ्रेश हो रहा है...',
    refreshTimeline: 'टाइमलाइन रिफ्रेश करें',
    rideCreated: 'राइड बनाई गई',
    driverAccepted: 'ड्राइवर ने स्वीकार किया',
    driverArrived: 'ड्राइवर पहुँचा',
    pinVerified: 'PIN सत्यापित',
    pinVerificationFailed: 'PIN सत्यापन विफल',
    rideCancelled: 'राइड रद्द हुई',
    pinExpired: 'PIN समाप्त हो गया',
    invalidPin: 'अमान्य PIN',
    changeAudit: 'परिवर्तन ऑडिट',
    loadingAuditHistory: 'ऑडिट इतिहास लोड हो रहा है…',
    change: 'परिवर्तन',
    actor: 'कर्ता:',
    system: 'सिस्टम',
    price: 'कीमत',
    cancellation: 'रद्दीकरण',
    cancelledBy: 'द्वारा रद्द',
    reason: 'कारण',
    ratings: 'रेटिंग्स',
    passengerRating: 'यात्री रेटिंग',
    notRated: 'रेटिंग नहीं दी गई',
    driverRating: 'ड्राइवर रेटिंग',
    comment: 'टिप्पणी',
    compliments: 'प्रशंसाएँ',
    none: 'कोई नहीं',
    tip: 'टिप',
    usersPageSubtitle: 'पंजीकृत RideEasy यात्रियों को प्रबंधित करें।',
    totalUsersLabel: 'कुल उपयोगकर्ता',
    searchUsers: 'नाम, ईमेल, फ़ोन या शहर से खोजें...',
    selected: 'चयनित',
    clear: 'साफ़ करें',
    delete: 'हटाएं',
    allUsers: 'सभी उपयोगकर्ता',
    usersShown: 'उपयोगकर्ता दिखाए गए',
    userShown: 'उपयोगकर्ता दिखाया गया',
    selectUsersBulk: 'बल्क कार्य करने के लिए उपयोगकर्ताओं का चयन करें',
    selectAllVisibleUsers: 'सभी दिखाई देने वाले उपयोगकर्ताओं का चयन करें',
    loadingUsers: 'उपयोगकर्ता लोड हो रहे हैं...',
    noUsersFound: 'कोई उपयोगकर्ता नहीं मिला',
    noUsersMatchSearch: 'कोई उपयोगकर्ता आपकी वर्तमान खोज से मेल नहीं खाता।',
    noRegisteredUsers: 'वर्तमान में कोई पंजीकृत उपयोगकर्ता नहीं है।',
    userDetails: 'उपयोगकर्ता विवरण',
    user: 'उपयोगकर्ता',
    email: 'ईमेल',
    status: 'स्थिति',
    actions: 'कार्रवाइयां',
    blocked: 'ब्लॉक किया गया',
    view: 'देखें',
    unblock: 'अनब्लॉक करें',
    block: 'ब्लॉक करें',
    userId: 'उपयोगकर्ता आईडी',
  },


  mr: {
    userReportUser: 'वापरकर्ता',
    loadingUsersReport: 'वापरकर्ता अहवाल लोड होत आहे…',
    usersActivitySubtitle: 'वापरकर्ता क्रियाकलाप आणि प्लॅटफॉर्म वापराचा आढावा',
    userActivity: 'वापरकर्ता क्रियाकलाप',
    userActivitySubtitle: 'वापरकर्त्यानुसार राइड क्रियाकलाप आणि खर्च',
    noUsersMatch: 'निवडलेल्या फिल्टरशी कोणताही वापरकर्ता जुळत नाही.',
    registered: 'नोंदणीकृत',
    safetyTitle: 'सुरक्षा',
    safetySubtitle: 'आपत्कालीन नियंत्रण आणि सुरक्षा संचालन',
    emergencyAlerts: 'आपत्कालीन अलर्ट',
    emergencyAlertsDescription: 'आपत्कालीन अलर्ट पहा आणि व्यवस्थापित करा',
    policeStations: 'पोलीस स्टेशन',
    policeStationsDescription: 'जवळील पोलीस स्टेशन्स व्यवस्थापित करा',
    safetySettings: 'सुरक्षा सेटिंग्ज',
    safetySettingsDescription: 'सुरक्षा सुविधा कॉन्फिगर करा',
    emergencyContacts: 'आपत्कालीन संपर्क',
    emergencyContactsDescription: 'आपत्कालीन संपर्क व्यवस्थापित करा',
    blockedUsersDescription: 'ब्लॉक केलेल्या वापरकर्त्यांची यादी पहा',
    safetyAndEmergency: 'सुरक्षा आणि आपत्काल',
    safetyControlCenter: 'सुरक्षा नियंत्रण केंद्र',
    monitorEmergencyAlarms: 'आपत्कालीन अलार्मचे निरीक्षण करा, प्रवासी सुरक्षा घटना व्यवस्थापित करा आणि ड्रायव्हर वाटप नियमांचे पुनरावलोकन करा.',
    safetySystem: 'सुरक्षा प्रणाली',
    emergencyAlarm: 'आपत्कालीन अलार्म',
    unknownRider: 'अज्ञात प्रवासी',
    unknownStatus: 'अज्ञात',
    acknowledge: 'स्वीकारा',
    resolveCallPolice: 'निराकरण करा आणि पोलिसांना कॉल करा',
    noEmergencyAlerts: 'कोणतेही आपत्कालीन अलर्ट नाहीत',
    noEmergencyAlertsDescription: 'सध्या कोणत्याही प्रवासी सुरक्षा घटनेकडे लक्ष देण्याची आवश्यकता नाही.',
    availablePoliceContacts: 'आपत्कालीन प्रतिसादासाठी उपलब्ध पोलीस संपर्क.',
    noPoliceStationData: 'पोलीस स्टेशनचा कोणताही डेटा उपलब्ध नाही.',
    call: 'कॉल करा',
    safetyConfiguration: 'सुरक्षा कॉन्फिगरेशन',
    driverAllocationRules: 'ड्रायव्हर वाटप नियम',
    ruleActive: 'नियम सक्रिय',
    passenger: 'प्रवासी',
    femalePassenger: 'महिला प्रवासी',
    requestsBikeRide: 'बाईक राइडची विनंती करते.',
    driverAllocation: 'ड्रायव्हर वाटप',
    femaleDriverOnly: 'फक्त महिला ड्रायव्हर',
    eligibleFemaleDriversOnly: 'फक्त पात्र महिला ड्रायव्हर',
    activeAllocationRule: 'सक्रिय वाटप नियम',
    femalePassengerBikeRule: 'महिला प्रवासी + बाईक राइड → फक्त महिला ड्रायव्हर.',
    femalePassengerBikeDescription: 'बाईक राइडची विनंती करणाऱ्या महिला प्रवाशांना फक्त पात्र महिला ड्रायव्हर्सना आपोआप असाइन केले जाते.',
    blockedUsersTitle: 'ब्लॉक केलेले वापरकर्ते',
    blockedUsersEmpty: 'ब्लॉक केलेले वापरकर्ते',
    blockedUsersNotConfigured: 'सध्याच्या सुरक्षा डेटा स्रोतामध्ये ब्लॉक केलेले वापरकर्ता व्यवस्थापन कॉन्फिगर केलेले नाही.',
    rideEasySupport: 'RideEasy सहाय्य',
    rideEasySupportDescription: 'आपत्कालीन आणि ग्राहक सहाय्य संपर्क व्यवस्थापित करा.',
    loadingRideEasySupport: 'RideEasy सहाय्य लोड होत आहे...',
    supportStatus: 'सहाय्य स्थिती',
    supportActive: 'RideEasy सहाय्य सध्या सक्रिय आहे.',
    supportInactive: 'RideEasy सहाय्य सध्या निष्क्रिय आहे.',
    name: 'नाव',
    phone: 'फोन',
    description: 'वर्णन',
    supportChangesUpdate: 'बदल विद्यमान RideEasy सहाय्य रेकॉर्ड अपडेट करतील.',
    supportRecordCreated: 'एक RideEasy सहाय्य रेकॉर्ड तयार केला जाईल.',
    saving: 'सेव्ह करत आहे...',
    saveSupport: 'सहाय्य सेव्ह करा',
    failedLoadSupport: 'RideEasy सहाय्य लोड करण्यात अयशस्वी.',
    supportUpdatedSuccessfully: 'RideEasy सहाय्य यशस्वीरित्या अपडेट केले.',
    failedUpdateSupport: 'RideEasy सहाय्य अपडेट करण्यात अयशस्वी.',

    helpSupport: 'मदत आणि सहाय्य',
    reportsPageTitle: 'अहवाल',
    reportsPageSubtitle: 'प्लॅटफॉर्म विश्लेषण आणि अहवाल पहा',

    loadingDriversReport: 'ड्रायव्हर अहवाल लोड होत आहे…',
    driversActivitySubtitle: 'ड्रायव्हर क्रियाकलाप आणि कामगिरीचा आढावा',
    driverPerformance: 'ड्रायव्हर कामगिरी',
    driverPerformanceSubtitle: 'ड्रायव्हर क्रियाकलाप, पूर्ण झालेल्या राइड्स आणि कमाई',
    noDriverRecords: 'ड्रायव्हर रेकॉर्ड आढळले नाहीत.',
    approval: 'मंजुरी',
    earnings: 'कमाई',    loadingBookingsReport: 'बुकिंग अहवाल लोड होत आहे…',
    bookingsActivitySubtitle: 'बुकिंग क्रियाकलाप आणि राइड स्थितीचा आढावा',
    bookingDetails: 'बुकिंग तपशील',
    bookingDetailsSubtitle: 'राइड, प्रवासी, ड्रायव्हर आणि भाड्याची माहिती',
    noBookingsFound: 'कोणतीही बुकिंग सापडली नाही',
    loadingEarningsReport: 'अर्निंग्स अहवाल लोड होत आहे…',
    fromCompletedRides: 'पूर्ण झालेल्या राइड्समधून',
    recordedCaptainEarnings: 'नोंदवलेली कॅप्टन कमाई',
    recordedPlatformFees: 'नोंदवलेली प्लॅटफॉर्म फी',
    appliedToCompletedRides: 'पूर्ण झालेल्या राइड्सवर लागू',
    completedRidesIncluded: 'या अहवालात समाविष्ट पूर्ण झालेल्या राइड्स',
    noCompletedRideEarnings: 'पूर्ण झालेल्या राइड्सची कोणतीही कमाई आढळली नाही',
    tryAnotherDateRange: 'दुसरी तारीख श्रेणी वापरून पहा.',
    earningsReport: 'कमाई अहवाल',
    earningsReportDescription: 'कमाईचे विश्लेषण पहा',
    bookingsReport: 'बुकिंग अहवाल',
    bookingsReportDescription: 'बुकिंगचे विश्लेषण पहा',
    driversReport: 'ड्रायव्हर अहवाल',
    driversReportDescription: 'ड्रायव्हर कामगिरी पहा',
    usersReport: 'वापरकर्ता अहवाल',
    usersReportDescription: 'वापरकर्ता विश्लेषण पहा',
    downloadReports: 'अहवाल डाउनलोड करा',
    downloadReportsDescription: 'CSV मध्ये डेटा डाउनलोड करा',
    backToReports: 'अहवालांवर परत जा',
    revenueAndEarningsOverview: 'पूर्ण झालेल्या राइडमधील महसूल आणि कमाईचा आढावा',
    allTime: 'सर्व कालावधी',
    last7Days: 'मागील 7 दिवस',
    last30Days: 'मागील 30 दिवस',
    last90Days: 'मागील 90 दिवस',
    discounts: 'सवलती',
    rideEarnings: 'राइडची कमाई',
    fare: 'भाडे',
    ongoing: 'सुरू',
    cancelled: 'रद्द',
    bookingValue: 'बुकिंग मूल्य',
    allStatuses: 'सर्व स्थिती',
    started: 'सुरू झाले',
    accepted: 'स्वीकारले',
    pending: 'प्रलंबित',
    route: 'मार्ग',
    online: 'ऑनलाइन',
    offline: 'ऑफलाइन',
    busy: 'व्यस्त',
    onlineDrivers: 'ऑनलाइन ड्रायव्हर',
    offlineDrivers: 'ऑफलाइन ड्रायव्हर',
    approvedDrivers: 'मंजूर ड्रायव्हर',
    searchDriver: 'ड्रायव्हर, फोन, वाहन किंवा शहर शोधा...',
    approved: 'मंजूर',
    usersReportSearch: 'वापरकर्ता, ईमेल, फोन किंवा शहर शोधा...',
    active: 'सक्रिय',
    activeUsers: 'सक्रिय वापरकर्ते',
    blockedUsers: 'ब्लॉक केलेले वापरकर्ते',
    totalRides: 'एकूण राइड',
    userSpending: 'वापरकर्ता खर्च',
    spending: 'खर्च',
    cancelledRidesInSelectedPeriod: 'निवडलेल्या कालावधीतील रद्द झालेल्या राइड',

    helpSupportSubtitle: 'मदत आणि सहाय्य मिळवा',
    needHelp: 'मदत हवी आहे?',
    needHelpText: 'RideEasy Admin Panel मध्ये काही समस्या येत असल्यास, मदतीसाठी सपोर्ट टीमशी संपर्क साधा.',
    adminSupport: 'अॅडमिन सहाय्य',
    adminSupportText: 'अकाउंट, डॅशबोर्ड, ड्रायव्हर, बुकिंग किंवा पेमेंटशी संबंधित समस्यांसाठी RideEasy प्रशासन टीमशी संपर्क साधा.',
    contactSupport: 'सपोर्टशी संपर्क साधा',
    contactSupportText: 'सपोर्ट संपर्क तपशील येथे उपलब्ध असतील.',
    supportCasesSubtitle: 'वापरकर्ता आणि ड्रायव्हर सपोर्ट प्रकरणांचे पुनरावलोकन आणि तपासणी करा',
    supportCases: 'सपोर्ट प्रकरणे',
    caseShown: 'प्रकरण दाखवले',
    casesShown: 'प्रकरणे दाखवली',
    searchSupportCases: 'प्रकरण, राइड, वापरकर्ता किंवा श्रेणी शोधा...',
    supportAll: 'सर्व',
    supportUser: 'वापरकर्ता',
    supportDriver: 'ड्रायव्हर',
    supportOpen: 'उघडे',
    supportInReview: 'पुनरावलोकनात',
    supportEscalated: 'एस्केलेटेड',
    supportResolved: 'निराकरण झाले',
    loadingSupportCases: 'सपोर्ट प्रकरणे लोड होत आहेत...',
    unableLoadSupportCases: 'सपोर्ट प्रकरणे लोड करता आली नाहीत',
    noSupportCases: 'कोणतेही सपोर्ट प्रकरण सापडले नाही',
    tryAnotherSearchFilter: 'दुसरा शोध किंवा फिल्टर वापरून पहा.',
    caseLabel: 'प्रकरण',
    closeCaseDetails: 'प्रकरणाचे तपशील बंद करा',
    priorityLabel: 'प्राधान्य',
    subject: 'विषय',
    userDriver: 'वापरकर्ता / ड्रायव्हर',
    rideIdLabel: 'राइड आयडी',
    rideStatus: 'राइड स्थिती',
    cancellationReason: 'रद्द करण्याचे कारण',
    cancellationFee: 'रद्दीकरण शुल्क',
    assignedOwner: 'नियुक्त व्यक्ती',
    investigationContext: 'तपास संदर्भ',
    statusHistory: 'स्थिती इतिहास',
    caseCreated: 'प्रकरण तयार केले',
    currentStatus: 'वर्तमान स्थिती',
    statusTransitionUnavailable: 'स्थिती बदलण्याची वेळ उपलब्ध नाही',
    supportHigh: 'उच्च',
    supportMedium: 'मध्यम',
    supportLow: 'कमी',
    supportPriority: 'प्राधान्य',



    invoicesPageTitle: 'इनव्हॉइस',
    invoicesPageSubtitle: 'राइड इनव्हॉइस, भाड्याची एकूण रक्कम आणि संबंधित पेमेंट माहिती पहा.',
    platformRevenue: 'प्लॅटफॉर्म महसूल',
    totalPaidAmount: 'एकूण भरलेली रक्कम',
    platformCommission: 'प्लॅटफॉर्म कमिशन',
    platformFeeEarned: 'मिळालेले प्लॅटफॉर्म शुल्क',
    driverShare: 'ड्रायव्हरचा हिस्सा',
    driverEarnings: 'ड्रायव्हरची कमाई',
    pendingPayouts: 'प्रलंबित पेआउट',
    driverSettlementsPending: 'ड्रायव्हर सेटलमेंट प्रलंबित',
    invoiceDetail: 'इनव्हॉइस तपशील',
    invoiceInformation: 'इनव्हॉइस माहिती',
    paymentLinkage: 'पेमेंट लिंक माहिती',
    fareAndTotal: 'भाडे आणि एकूण',
    authoritativeInvoiceTotal: 'अधिकृत इनव्हॉइस एकूण',
    invoiceList: 'इनव्हॉइस सूची',
    invoiceTotalSource: 'इनव्हॉइसची एकूण रक्कम अधिकृत राइड रकमेतून घेतली आहे.',
    searchInvoice: 'इनव्हॉइस, राइड, ग्राहक, रक्कम शोधा…',
    loadingInvoices: 'इनव्हॉइस लोड होत आहेत…',
    noRideInvoices: 'कोणतेही राइड इनव्हॉइस उपलब्ध नाहीत.',
    noInvoicesMatch: 'तुमच्या शोधाशी कोणतेही इनव्हॉइस जुळत नाहीत.',
    invoice: 'इनव्हॉइस',
    paymentId: 'पेमेंट आयडी',
    fareConfigurationTitle: 'भाडे कॉन्फिगरेशन',
    configureVersionedFares: 'राइड प्रकार आणि शहर / झोननुसार नियंत्रित प्रभावी कालावधीसह आवृत्तीचे भाडे कॉन्फिगर करा.',
    fareVersions: 'भाडे आवृत्त्या',
    editDraftFare: 'ड्राफ्ट भाडे संपादित करा',
    createFareConfiguration: 'भाडे कॉन्फिगरेशन तयार करा',
    activeHistoricalVersions: 'सक्रिय आणि जुन्या आवृत्त्या शांतपणे बदलता येत नाहीत.',
    cancelEdit: 'संपादन रद्द करा',
    rideTypeLabel: 'राइड प्रकार',
    cityZoneLabel: 'शहर / झोन',
    distanceRate: 'अंतर दर / किमी',
    timeRate: 'वेळ दर / मिनिट',
    minimumFare: 'किमान भाडे',
    fees: 'शुल्क',
    registrationFee: 'नोंदणी शुल्क',
    minimumWalletBalance: 'किमान वॉलेट शिल्लक',
    taxPercentage: 'कर (%)',
    effectiveFrom: 'प्रभावी पासून',
    effectiveTo: 'प्रभावी पर्यंत',
    saveAsDraft: 'ड्राफ्ट म्हणून सेव्ह करा',
    activationDescription: 'अॅक्टिव्हेशन ही स्वतंत्र पुष्टी केलेली कृती आहे आणि ओव्हरलॅप होणाऱ्या सक्रिय कालावधीविरुद्ध तिची पडताळणी केली जाते.',
    calculating: 'गणना होत आहे…',
    previewFare: 'भाड्याचे पूर्वावलोकन',
    updateDraft: 'ड्राफ्ट अपडेट करा',
    createDraft: 'ड्राफ्ट तयार करा',
    farePreview: 'भाडे पूर्वावलोकन',
    fareConfigurationList: 'भाडे कॉन्फिगरेशन सूची',
    fareConfigurationListSubtitle: 'राइड प्रकार, शहर / झोन, आवृत्ती, स्थिती आणि प्रभावी कालावधी.',
    version: 'आवृत्ती',
    noFareConfigurations: 'कोणतेही भाडे कॉन्फिगरेशन आढळले नाही.',
    edit: 'संपादित करा',
    activate: 'सक्रिय करा',
    deactivate: 'निष्क्रिय करा',
    history: 'इतिहास',
    baseFare: 'मूळ भाडे',
    discount: 'सूट',
    paymentAmount: 'पेमेंट रक्कम',
    date: 'तारीख',
    total: 'एकूण',
    ride: 'राइड',
    dashboard: 'डॅशबोर्ड',
    users: 'वापरकर्ते',
    drivers: 'ड्रायव्हर्स',
    vehicles: 'वाहने',
    manageRegisteredVehicles: 'नोंदणीकृत वाहने आणि पडताळणी स्थिती व्यवस्थापित करा',
    allVehicles: 'सर्व वाहने',
    searchVehicles: 'वाहन क्रमांक, प्रकार, मॉडेल किंवा ड्रायव्हर शोधा...',
    vehicleStatusLabel: 'स्थिती',
    noVehiclesFound: 'कोणतीही वाहने आढळली नाहीत',
    noVehiclesMatch: 'तुमच्या सध्याच्या शोधाशी किंवा फिल्टरशी कोणतेही वाहन जुळत नाही.',
    loadingVehicles: 'वाहने लोड होत आहेत...',
    vehicleDetails: 'वाहन तपशील',
    unnamedDriver: 'अनामिक ड्रायव्हर',
    vehicleModel: 'वाहन मॉडेल',
    driverEmail: 'ड्रायव्हर ईमेल',
    driverPhone: 'ड्रायव्हर फोन',
    rcStatus: 'आरसी स्थिती',
    insuranceStatus: 'विमा स्थिती',
    registrationDate: 'नोंदणी तारीख',
    vehicleStatus: 'वाहन स्थिती',
    pendingVerification: 'पडताळणी प्रलंबित',
    vehicleColumn: 'वाहन',
    modelColumn: 'मॉडेल',
    driverColumn: 'ड्रायव्हर',
    vehicleRecordsSource: 'वाहन रेकॉर्ड नोंदणीकृत ड्रायव्हर्सकडून घेतले जातात.',

    verification: 'पडताळणी',
    verificationQueue: 'पडताळणी रांग',
    valid: 'वैध',
    expiringSoon: 'लवकर कालबाह्य होणार',
    reviewDriverVerificationInfo: 'ड्रायव्हर पडताळणी माहितीचे पुनरावलोकन करा',
    verificationDocuments: 'पडताळणी दस्तऐवज',
    documentReview: 'दस्तऐवज पुनरावलोकन',
    statusLabel: 'स्थिती',
    versionLabel: 'आवृत्ती',
    documentInformation: 'दस्तऐवज माहिती',
    noExtractedDocumentInformation: 'दस्तऐवजाची कोणतीही माहिती उपलब्ध नाही',
    apiDidNotProvideDocumentFields: 'API ने अतिरिक्त दस्तऐवज फील्ड उपलब्ध करून दिले नाहीत.',
    documentPreview: 'दस्तऐवज पूर्वावलोकन',
    openDocument: 'उघडा',
    loadingDocumentPreview: 'दस्तऐवज पूर्वावलोकन लोड होत आहे...',
    previewUnavailable: 'पूर्वावलोकन उपलब्ध नाही',
    authorizedDocumentPreviewUnavailable: 'अधिकृत दस्तऐवज पूर्वावलोकन लोड करता आले नाही.',
    back: 'मागे',
    unableToLoadVerificationQueue: 'पडताळणी रांग लोड करता आली नाही',
    rejectVerification: 'पडताळणी नाकारा',
    unableToLoadDocumentPreview: 'दस्तऐवज पूर्वावलोकन लोड करता आले नाही',
    viewDocuments: 'दस्तऐवज पहा',
    noDocumentsReturned: 'ड्रायव्हर API ने या ड्रायव्हरसाठी कोणतेही दस्तऐवज रेकॉर्ड परत केले नाहीत.',
    noDocumentsAvailable: 'कोणतेही दस्तऐवज उपलब्ध नाहीत',
    uploadDocument: 'दस्तऐवज अपलोड करा',
    notSubmitted: 'सादर केलेले नाही',
    submitted: 'सादर केले',
    psychologicalAssessment: 'मानसशास्त्रीय मूल्यांकन',
    eyeExamination: 'नेत्र तपासणी',
    medicalFitness: 'वैद्यकीय तंदुरुस्ती',
    policeVerification: 'पोलीस पडताळणी',
    reviewCompliance: 'ड्रायव्हरच्या अनिवार्य अनुपालन आवश्यकतांचे पुनरावलोकन करा.',
    captainCompliance: 'कॅप्टन अनुपालन',
    rejectionReason: 'नकाराचे कारण',
    subscriptionExpiry: 'सदस्यता कालबाह्यता',
    overallStatus: 'एकूण स्थिती',
    lastUpdated: 'शेवटचे अपडेट',
    licence: 'परवाना',
    vehicleNumber: 'वाहन क्रमांक',
    vehicleType: 'वाहन प्रकार',
    driverDetails: 'ड्रायव्हर तपशील',
    reviewVerificationRequests: 'ड्रायव्हर पडताळणी विनंत्या आणि सादर केलेल्या दस्तऐवजांचे पुनरावलोकन करा.',
    rides: 'राइड्स',
    liveOperations: 'लाइव्ह ऑपरेशन्स',
    liveOpsPageSubtitle: 'ड्रायव्हरची उपलब्धता आणि सक्रिय राइडची स्थिती तपासा.',
    liveOpsUpdatesConnected: 'लाइव्ह अपडेट्स कनेक्ट झाले आहेत',
    liveOpsReconnecting: 'लाइव्ह अपडेट्स पुन्हा कनेक्ट होत आहेत…',
    liveOpsUpdatesDisabled: 'लाइव्ह अपडेट्स बंद आहेत',
    liveOpsUpdatesDisconnected: 'लाइव्ह अपडेट्स डिस्कनेक्ट झाले आहेत',
    liveOpsAvailableDrivers: 'उपलब्ध ड्रायव्हर',
    liveOpsDriversOnActiveRides: 'सक्रिय राइडवरील ड्रायव्हर',
    liveOpsCurrentlyUnavailable: 'सध्या अनुपलब्ध',
    liveOpsLiveMap: 'लाइव्ह नकाशा',
    liveOpsLive: 'लाइव्ह',
    liveOpsStale: 'जुने',
    liveOpsDriverActiveLocations: 'ड्रायव्हर आणि सक्रिय राइडची स्थाने',
    liveOpsLoadingMap: 'लाइव्ह नकाशा लोड होत आहे...',
    liveOpsFetchingLocations: 'ड्रायव्हर आणि सक्रिय राइडची स्थाने मिळवली जात आहेत.',
    liveOpsUnableLoadMap: 'लाइव्ह नकाशा लोड करता आला नाही',
    liveOpsLocationsCouldNotLoad: 'ड्रायव्हर आणि सक्रिय राइडची स्थाने लोड करता आली नाहीत.',
    liveOpsNoLocations: 'कोणतीही लाइव्ह स्थाने उपलब्ध नाहीत',
    liveOpsLocationsAppearHere: 'ड्रायव्हर आणि सक्रिय राइडची स्थाने येथे दिसतील.',
    liveOpsDriverStatus: 'ड्रायव्हर स्थिती',
    liveOpsDriver: 'ड्रायव्हर',
    liveOpsDrivers: 'ड्रायव्हर',
    liveOpsShown: 'दाखवले',
    liveOpsSearchDriver: 'ड्रायव्हर शोधा...',
    liveOpsAllStatuses: 'सर्व स्थिती',
    liveOpsLoadingStatus: 'ड्रायव्हरची स्थिती लोड होत आहे...',
    liveOpsTryAgain: 'पुन्हा प्रयत्न करा',
    liveOpsNoDrivers: 'कोणतेही ड्रायव्हर सापडले नाहीत',
    liveOpsChangeFilter: 'तुमचा शोध किंवा स्थिती फिल्टर बदला.',
    liveOpsUnnamedDriver: 'नाव नसलेला ड्रायव्हर',
    liveOpsNoContact: 'संपर्क उपलब्ध नाही',
    liveOpsVehicle: 'वाहन',
    liveOpsStatus: 'स्थिती',
    liveOpsOnline: 'ऑनलाइन',
    liveOpsBusy: 'व्यस्त',
    liveOpsOffline: 'ऑफलाइन',
    liveOpsUnableLoadDrivers: 'ड्रायव्हरची लाइव्ह स्थिती लोड करता आली नाही.',

    couponPageTitle: 'कूपन्स',
    couponPageSubtitle: 'प्रमोशनल कूपन्स तयार करा आणि व्यवस्थापित करा.',
    couponCreate: 'कूपन तयार करा',
    couponSearch: 'कूपन कोड शोधा...',
    couponAllStatus: 'सर्व स्थिती',
    couponActive: 'सक्रिय',
    couponExpired: 'कालबाह्य',
    couponCode: 'कूपन कोड',
    couponDiscount: 'सूट',
    couponMinRide: 'किमान राइड',
    couponValidity: 'वैधता',
    couponUsage: 'वापर',
    couponStatus: 'स्थिती',
    couponActions: 'कृती',
    couponEdit: 'संपादित करा',
    couponDelete: 'हटवा',
    couponNoCoupons: 'कोणतेही कूपन सापडले नाही.',
    couponEditTitle: 'कूपन संपादित करा',
    couponCreateTitle: 'कूपन तयार करा',
    couponUpdateDetails: 'कूपनचे तपशील अपडेट करा.',
    couponCreateForRiders: 'राइडर्ससाठी प्रमोशनल कूपन तयार करा.',
    couponCodeRequired: 'कूपन कोड *',
    couponDiscountTypeRequired: 'सूट प्रकार *',
    couponPercentage: 'टक्केवारी (%)',
    couponFixedAmount: 'निश्चित रक्कम (₹)',
    couponDiscountValueRequired: 'सूट रक्कम *',
    couponMinimumRideRequired: 'किमान राइड रक्कम *',
    couponMaximumDiscount: 'कमाल सूट',
    couponValidFromRequired: 'वैध प्रारंभ *',
    couponValidUntilRequired: 'वैध समाप्ती *',
    couponUsageLimitRequired: 'वापर मर्यादा *',
    couponCancel: 'रद्द करा',
    couponUpdate: 'कूपन अपडेट करा',
    couponSave: 'कूपन सेव्ह करा',
    couponFillRequired: 'कृपया सर्व आवश्यक फील्ड भरा.',
    couponLoadFailed: 'कूपन्स लोड करता आले नाहीत.',
    couponSaveFailed: 'कूपन सेव्ह करता आले नाही.',
    couponDeleteFailed: 'कूपन हटवता आले नाही.',
    couponDeleteConfirm: 'कूपन हटवा',
    couponExample: 'उदा.',

    finance: 'वित्त',
    coupons: 'कूपन्स',
    payments: 'पेमेंट्स',
    sos: 'SOS',
    support: 'सपोर्ट',
    reports: 'अहवाल',
    auditLogs: 'ऑडिट लॉग्स',
    auditLogsSubtitle: 'अॅडमिन आणि सिस्टम क्रियाकलापांचे पुनरावलोकन करा.',
    allActors: 'सर्व एक्टर्स',
    actorType: 'एक्टर प्रकार',
    allTargets: 'सर्व लक्ष्य',
    target: 'लक्ष्य',
    timestamp: 'टाइमस्टॅम्प',
    loadingAuditLogs: 'ऑडिट लॉग्स लोड होत आहेत…',
    failedToLoadAuditLogs: 'ऑडिट लॉग्स लोड करता आले नाहीत.',
    retry: 'पुन्हा प्रयत्न करा',
    noAuditLogsFound: 'कोणतेही ऑडिट लॉग आढळले नाहीत',
    auditLogsEmptyDescription: 'ऑडिट इव्हेंट नोंदवले गेल्यावर येथे क्रियाकलाप दिसेल.',
    notifications: 'सूचना',
    notificationsSubtitle: 'महत्त्वाच्या RideEasy गतिविधींबद्दल अपडेट राहा.',
    markAllAsRead: 'सर्व वाचलेले म्हणून चिन्हांकित करा',
    allNotifications: 'सर्व',
    emergencyNotifications: 'आपत्कालीन',
    rideNotifications: 'राइड्स',
    driverNotifications: 'ड्रायव्हर्स',
    systemNotifications: 'सिस्टम',
    searchNotifications: 'सूचना शोधा…',
    unableToLoadNotifications: 'सूचना लोड करता आल्या नाहीत',
    loadingNotifications: 'सूचना लोड होत आहेत…',
    noNotifications: 'कोणत्याही सूचना नाहीत',
    allCaughtUp: 'तुम्ही सर्व सूचनांबाबत अपडेट आहात.',
    noFilteredNotifications: 'सध्याच्या API मधून कोणत्याही {filter} सूचना उपलब्ध नाहीत.',
    emergencyAlert: 'आपत्कालीन अलर्ट',
    highPriority: 'उच्च प्राधान्य',
    passengerUser: 'प्रवासी / वापरकर्ता',
    location: 'स्थान',
    city: 'शहर',
    emergencyTime: 'आपत्कालीन वेळ',
    notAvailable: 'उपलब्ध नाही',
    acknowledged: 'स्वीकारले',
    resolved: 'निराकरण झाले',
    viewEmergency: 'आपत्कालीन माहिती पहा',
    viewDetails: 'तपशील पहा',
    resolveAndCallPolice: 'निराकरण करा आणि पोलिसांना कॉल करा',
    emergencyDetails: 'आपत्कालीन तपशील',
    emergencyAlertInformation: 'आपत्कालीन अलर्टची माहिती',
    close: 'बंद करा',
    rideEasyNotification: 'RideEasy सूचना',
    newActivityReceived: 'नवीन गतिविधी प्राप्त झाली.',
    newRideArrived: 'नवीन राइड प्राप्त झाली',
    newRideRequestArrived: 'नवीन राइड विनंती प्राप्त झाली आहे.',
    driverOnline: 'ड्रायव्हर ऑनलाइन',
    driverOffline: 'ड्रायव्हर ऑफलाइन',
    driverNowOnline: 'एक ड्रायव्हर आता ऑनलाइन आहे.',
    driverGoneOffline: 'एक ड्रायव्हर ऑफलाइन झाला आहे.',
    rideAccepted: 'राइड स्वीकारली',
    driverAcceptedRide: 'एका ड्रायव्हरने राइड स्वीकारली आहे.',
    rideStarted: 'राइड सुरू झाली',
    rideHasStarted: 'एक राइड सुरू झाली आहे.',
    rideCompleted: 'राइड पूर्ण झाली',
    rideHasBeenCompleted: 'एक राइड पूर्ण झाली आहे.',
    unableToAcknowledgeEmergency: 'आपत्काल स्वीकारता आला नाही',
    emergencyResolvedNoPolicePhone: 'आपत्कालाचे निराकरण झाले, परंतु जवळच्या पोलिस स्टेशनचा फोन नंबर उपलब्ध नाही.',
    unableToResolveEmergency: 'आपत्कालाचे निराकरण करता आले नाही',
    rolesPermissions: 'भूमिका आणि परवानग्या',
    pricing: 'किंमत निर्धारण',
    settings: 'सेटिंग्ज',
    manageAdminPreferences: 'अॅडमिन प्राधान्ये व्यवस्थापित करा',
    profileSettings: 'प्रोफाइल सेटिंग्ज',
    adminSettings: 'अॅडमिन / सेटिंग्ज',
    manageAdminProfile: 'तुमचे अॅडमिन प्रोफाइल व्यवस्थापित करा.',
    fullName: 'पूर्ण नाव',
    emailAddress: 'ईमेल पत्ता',
    phoneNumber: 'फोन नंबर',
    adminRole: 'अॅडमिन भूमिका',
    administration: 'प्रशासन',
    profileChangesSaved: 'प्रोफाइलमधील बदल यशस्वीरित्या जतन केले.',
    cancel: 'रद्द करा',
    saveChanges: 'बदल जतन करा',

    changePassword: 'पासवर्ड बदला',
    changePasswordSubtitle: 'तुमचा अॅडमिन अकाउंट पासवर्ड अपडेट करा.',
    currentPasswordLabel: 'सध्याचा पासवर्ड',
    newPasswordLabel: 'नवीन पासवर्ड',
    confirmNewPasswordLabel: 'नवीन पासवर्डची पुष्टी करा',
    enterCurrentPassword: 'सध्याचा पासवर्ड प्रविष्ट करा',
    enterNewPassword: 'नवीन पासवर्ड प्रविष्ट करा',
    confirmNewPassword: 'नवीन पासवर्ड पुन्हा प्रविष्ट करा',
    fillInAllFields: 'कृपया सर्व फील्ड भरा.',
    newPasswordMinLength: 'नवीन पासवर्ड किमान 6 अक्षरांचा असावा.',
    passwordConfirmationMismatch: 'नवीन पासवर्ड आणि पुष्टी जुळत नाही.',
    passwordChangedSuccessfully: 'पासवर्ड यशस्वीरित्या बदलला.',
    unableToChangePassword: 'पासवर्ड बदलता आला नाही.',
    changingPassword: 'पासवर्ड बदलला जात आहे…',
    notificationSettings: 'सूचना सेटिंग्ज',
    appSettings: 'अॅप सेटिंग्ज',
    appSettingsTitle: 'अॅप सेटिंग्ज',
    managePlatformConfiguration: 'सामान्य प्लॅटफॉर्म कॉन्फिगरेशन व्यवस्थापित करा.',
    maintenanceMode: 'मेंटेनन्स मोड',
    maintenanceModeDescription: 'प्लॅटफॉर्म तात्पुरता मेंटेनन्स मोडमध्ये ठेवा.',
    rideBooking: 'राइड बुकिंग',
    rideBookingDescription: 'वापरकर्त्यांना नवीन राइड बुकिंग तयार करण्याची परवानगी द्या.',
    driverRegistration: 'ड्रायव्हर नोंदणी',
    driverRegistrationDescription: 'नवीन ड्रायव्हर्सना प्लॅटफॉर्मवर नोंदणी करण्याची परवानगी द्या.',
    loadingSettings: 'सेटिंग्ज लोड होत आहेत…',
    unableToSaveAppSettings: 'अॅप सेटिंग्ज सेव्ह करता आल्या नाहीत.',
    savingSettings: 'सेव्ह केले जात आहे…',
    saveSettings: 'सेटिंग्ज सेव्ह करा',
    updateAdminProfile: 'अॅडमिन प्रोफाइल अपडेट करा',
    updateAdminPassword: 'अॅडमिन पासवर्ड अपडेट करा',
    configureNotifications: 'सूचना कॉन्फिगर करा',
    generalAppConfigurations: 'सामान्य अॅप कॉन्फिगरेशन',
    logOut: 'लॉग आउट',

    language: 'भाषा',
    selectPreferredLanguage: 'तुमची पसंतीची अॅडमिन पॅनेल भाषा निवडा.',
    backToSettings: 'सेटिंग्जवर परत जा',
    saveLanguage: 'भाषा सेव्ह करा',
    languagePreferenceSaved: 'भाषेची पसंती यशस्वीरित्या सेव्ह झाली.',
    english: 'इंग्रजी',
    hindi: 'हिंदी',
    marathi: 'मराठी',
    switchToLightMode: 'लाइट मोडवर स्विच करा',
    switchToDarkMode: 'डार्क मोडवर स्विच करा',
    lightMode: 'लाइट मोड',
    darkMode: 'डार्क मोड',
    refresh: 'रिफ्रेश',
    overviewPlatform: 'तुमच्या प्लॅटफॉर्मचा आढावा',
    totalUsers: 'एकूण वापरकर्ते',
    totalDrivers: 'एकूण ड्रायव्हर्स',
    totalBookings: 'एकूण बुकिंग्स',
    totalRevenue: 'एकूण महसूल',
    completedRides: 'पूर्ण झालेल्या राइड्स',
    successfullyFinishedTrips: 'यशस्वीरित्या पूर्ण झालेल्या ट्रिप्स',
    totalCompleted: 'एकूण पूर्ण',
    topDriver: 'टॉप ड्रायव्हर',
    topDriverSubtitle: 'सर्वाधिक पूर्ण राइड्स असलेला ड्रायव्हर',
    noDriverData: 'ड्रायव्हरचा डेटा उपलब्ध नाही',
    completedRidesLabel: 'पूर्ण झालेल्या राइड्स',
    pendingActions: 'प्रलंबित कामे',
    pendingActionsSubtitle: 'ज्या बाबींवर तुमच्या लक्षाची आवश्यकता असू शकते',
    driverVerification: 'ड्रायव्हर पडताळणी',
    documentsPending: 'कागदपत्रे प्रलंबित',
    complaintsToReview: 'पुनरावलोकनासाठी तक्रारी',
    failedPayments: 'अयशस्वी पेमेंट्स',
    reviewNow: 'आता पुनरावलोकन करा',
    recentActivity: 'अलीकडील क्रियाकलाप',
    newDriverRegistered: 'नवीन ड्रायव्हर नोंदणीकृत',
    documentSubmitted: 'कागदपत्र सादर केले',
    paymentReceived: 'पेमेंट प्राप्त झाले',
    live: 'लाइव्ह',
    loadingDashboard: 'डॅशबोर्ड लोड होत आहे...',
    unableToLoadDashboard: 'डॅशबोर्ड लोड करता आला नाही',
    tryAgain: 'पुन्हा प्रयत्न करा',
    recently: 'अलीकडे',
    justNow: 'आत्ताच',
    minAgo: 'मिनिटांपूर्वी',
    hrAgo: 'तासांपूर्वी',
    dAgo: 'दिवसांपूर्वी',
    rating: 'रेटिंग',
    driverFallback: 'ड्रायव्हर',
    driverDocuments: 'ड्रायव्हरची कागदपत्रे',
    completedRideFallback: 'पूर्ण झालेली राइड',
    ridePayment: 'राइड पेमेंट',
    ridesPageSubtitle: 'सर्व राइड्सचे व्यवस्थापन आणि निरीक्षण करा.',
    paymentReconciliation: 'पेमेंट रीकन्सिलिएशन',
    paymentReconciliationSubtitle: 'अपेक्षित आणि भरलेल्या रकमेची, ड्रायव्हर सेटलमेंट स्थितीची आणि रीकन्सिलिएशन निकालांची तुलना करा.',
    expectedAmount: 'अपेक्षित रक्कम',
    paidAmount: 'भरलेली रक्कम',
    paymentStatus: 'पेमेंट स्थिती',
    reconciliation: 'रीकन्सिलिएशन',
    settlementStatus: 'सेटलमेंट स्थिती',
    driverEarning: 'ड्रायव्हरची कमाई',
    platformFee: 'प्लॅटफॉर्म शुल्क',
    reconciliationDetails: 'रीकन्सिलिएशन तपशील',
    paymentSettlementReconciliationInfo: 'पेमेंट, सेटलमेंट आणि रीकन्सिलिएशनची माहिती',
    transactionId: 'व्यवहार आयडी',
    paymentMethod: 'पेमेंट पद्धत',
    paymentType: 'पेमेंट प्रकार',
    providerReference: 'प्रदाता संदर्भ',
    webhookEventId: 'वेबहुक इव्हेंट आयडी',
    createdAt: 'तयार केले',
    updatedAt: 'अपडेट केले',
    allDrivers: 'सर्व ड्रायव्हर्स',
    unnamedUser: 'नाव नसलेला वापरकर्ता',
    searchRides: 'शहर, रूट, प्रवासी, ड्रायव्हर, आयडी शोधा…',
    deleteSelected: 'निवडलेले हटवा',
    loadingRides: 'राइड्स लोड होत आहेत…',
    dateUnavailable: 'तारीख उपलब्ध नाही',
    pickup: 'पिकअप',
    drop: 'ड्रॉप',
    driver: 'ड्रायव्हर',
    unassigned: 'असाइन केलेले नाही',
    vehicle: 'वाहन',
    distance: 'अंतर',
    bookedFare: 'बुक केलेले भाडे',
    finalFare: 'अंतिम भाडे',
    paymentPending: 'पेमेंट प्रलंबित',
    difference: 'फरक',
    payment: 'पेमेंट',
    when: 'वेळ',
    rider: 'प्रवासी',
    pickupDestination: 'पिकअप → गंतव्य',
    completed: 'पूर्ण झाले',
    action: 'कृती',
    noRidesYet: 'अद्याप डेटाबेसमध्ये कोणतीही राइड नाही. Status मध्ये All निवडा किंवा बॅकएंड कनेक्शन तपासा.',
    noRidesMatch: 'तुमच्या शोधाशी किंवा फिल्टरशी कोणतीही राइड जुळत नाही.',
    rideDetails: 'राइड तपशील',
    rideId: 'राइड आयडी',
    chargedAmount: 'आकारलेली रक्कम',
    created: 'तयार केले',
    paymentBreakdown: 'पेमेंट तपशील',
    userPaid: 'वापरकर्त्याने भरले',
    driverGets: 'ड्रायव्हरला मिळते',
    adminPlatformFee: 'अॅडमिन / प्लॅटफॉर्म शुल्क',
    assignmentSummary: 'असाइनमेंट सारांश',
    currentDriver: 'सध्याचा ड्रायव्हर',
    currentRideState: 'सध्याची राइड स्थिती',
    assignmentTime: 'असाइनमेंट वेळ',
    notAssigned: 'असाइन केलेले नाही',
    eta: 'अंदाजे वेळ',
    matchingAttempts: 'मॅचिंग प्रयत्न',
    driverUnavailable: 'ड्रायव्हर उपलब्ध नाही',
    offeredAt: 'ऑफर केले',
    respondedAt: 'प्रतिक्रिया दिली',
    assignmentTimeline: 'असाइनमेंट टाइमलाइन',
    refreshing: 'रिफ्रेश होत आहे...',
    refreshTimeline: 'टाइमलाइन रिफ्रेश करा',
    rideCreated: 'राइड तयार झाली',
    driverAccepted: 'ड्रायव्हरने स्वीकारले',
    driverArrived: 'ड्रायव्हर पोहोचला',
    pinVerified: 'PIN सत्यापित',
    pinVerificationFailed: 'PIN सत्यापन अयशस्वी',
    rideCancelled: 'राइड रद्द झाली',
    pinExpired: 'PIN कालबाह्य झाला',
    invalidPin: 'अवैध PIN',
    changeAudit: 'बदल ऑडिट',
    loadingAuditHistory: 'ऑडिट इतिहास लोड होत आहे…',
    change: 'बदल',
    actor: 'कर्ता:',
    system: 'सिस्टम',
    price: 'किंमत',
    cancellation: 'रद्द करणे',
    cancelledBy: 'यांनी रद्द केले',
    reason: 'कारण',
    ratings: 'रेटिंग्स',
    passengerRating: 'प्रवासी रेटिंग',
    notRated: 'रेटिंग दिलेले नाही',
    driverRating: 'ड्रायव्हर रेटिंग',
    comment: 'टिप्पणी',
    compliments: 'कौतुक',
    none: 'काहीही नाही',
    tip: 'टिप',
    usersPageSubtitle: 'नोंदणीकृत RideEasy प्रवाशांचे व्यवस्थापन करा.',
    totalUsersLabel: 'एकूण वापरकर्ते',
    searchUsers: 'नाव, ईमेल, फोन किंवा शहराने शोधा...',
    selected: 'निवडलेले',
    clear: 'साफ करा',
    delete: 'हटवा',
    allUsers: 'सर्व वापरकर्ते',
    usersShown: 'वापरकर्ते दाखवले',
    userShown: 'वापरकर्ता दाखवला',
    selectUsersBulk: 'बल्क क्रिया करण्यासाठी वापरकर्ते निवडा',
    selectAllVisibleUsers: 'दिसणारे सर्व वापरकर्ते निवडा',
    loadingUsers: 'वापरकर्ते लोड होत आहेत...',
    noUsersFound: 'कोणतेही वापरकर्ते सापडले नाहीत',
    noUsersMatchSearch: 'तुमच्या सध्याच्या शोधाशी कोणताही वापरकर्ता जुळत नाही.',
    noRegisteredUsers: 'सध्या कोणतेही नोंदणीकृत वापरकर्ते नाहीत.',
    userDetails: 'वापरकर्ता तपशील',
    user: 'वापरकर्ता',
    email: 'ईमेल',
    status: 'स्थिती',
    actions: 'क्रिया',
    blocked: 'ब्लॉक केलेले',
    view: 'पहा',
    unblock: 'अनब्लॉक करा',
    block: 'ब्लॉक करा',
    userId: 'वापरकर्ता आयडी',
    adminVerification: 'प्रशासक पडताळणी',
    all: 'सर्व',
    approve: 'मंजूर करा',
    complianceDocumentUploaded: 'अनुपालन दस्तऐवज यशस्वीरित्या अपलोड केला.',
    complianceStatusUpdated: 'अनुपालन स्थिती यशस्वीरित्या अपडेट केली.',
    confirmReject: 'नकाराची पुष्टी करा',
    documentExpired: 'दस्तऐवज कालबाह्य',
    documentStatus: 'दस्तऐवज स्थिती',
    documentUnreadable: 'दस्तऐवज वाचता येत नाही',
    documentVerification: 'दस्तऐवज पडताळणी',
    driverIdMissingApprove: 'ड्रायव्हर ID उपलब्ध नाही. पडताळणी मंजूर करता येत नाही.',
    driverIdMissingCompliance: 'ड्रायव्हर ID उपलब्ध नाही. अनुपालन स्थिती अपडेट करता येत नाही.',
    driverIdMissingReject: 'ड्रायव्हर ID उपलब्ध नाही. पडताळणी नाकारता येत नाही.',
    driverIdMissingUpload: 'ड्रायव्हर ID उपलब्ध नाही. दस्तऐवज अपलोड करता येत नाही.',
    enterRejectionReason: 'नकाराचे कारण प्रविष्ट करा',
    expired: 'कालबाह्य',
    expiry: 'कालबाह्यता',
    loadingVerificationQueue: 'पडताळणी यादी लोड होत आहे…',
    nextPage: 'पुढील पृष्ठ',
    noMatchingVerifications: 'कोणत्याही पडताळण्या आढळल्या नाहीत.',
    noVerificationRequests: 'पडताळणी विनंत्या आढळल्या नाहीत.',
    optional: 'पर्यायी',
    pendingReview: 'पुनरावलोकन प्रलंबित',
    previousPage: 'मागील पृष्ठ',
    processing: 'प्रक्रिया सुरू आहे…',
    reUploadRequired: 'पुन्हा अपलोड आवश्यक',
    reasonCategory: 'कारण श्रेणी',
    reject: 'नकार द्या',
    rejectReasonMandatory: 'नकाराचे कारण आवश्यक आहे.',
    rejected: 'नाकारले',
    rejecting: 'नकार देत आहे…',
    rejectionReasonBackend: 'नकाराचे कारण',
    searchVerification: 'पडताळणी विनंत्या शोधा',
    selectReasonCategory: 'कारण श्रेणी निवडा',
    underReview: 'पुनरावलोकन सुरू आहे',
    uploadDate: 'अपलोड तारीख',
    verificationApprovedSuccess: 'पडताळणी यशस्वीरित्या मंजूर केली.',
    verificationRejectedSuccess: 'पडताळणी यशस्वीरित्या नाकारली.',

    servicesPageSubtitle: 'सेवा पर्याय आणि किंमत व्यवस्थापित करा',
    serviceList: 'सेवा यादी',
    serviceListDescription: 'सर्व सेवा पहा आणि व्यवस्थापित करा',
    serviceCategories: 'सेवा श्रेणी',
    serviceCategoriesDescription: 'सेवा श्रेणी व्यवस्थापित करा',
    pricingSettings: 'किंमत सेटिंग्ज',
    pricingSettingsDescription: 'किंमत नियम कॉन्फिगर करा',
    surgeSettings: 'सर्ज सेटिंग्ज',
    surgeSettingsDescription: 'सर्ज किंमत व्यवस्थापित करा',
    serviceAvailability: 'सेवा उपलब्धता',
    serviceAvailabilityDescription: 'सेवा उपलब्धता व्यवस्थापित करा',
    manageRideEasyServices: 'RideEasy सेवा व्यवस्थापित करा',
    addService: 'सेवा जोडा',
    unableLoadServices: 'सेवा लोड करता आल्या नाहीत',
    searchServices: 'सेवा शोधा...',
    serviceConfiguration: 'सेवा कॉन्फिगरेशन',
    editService: 'सेवा संपादित करा',
    allFareAmountsInINR: 'सर्व भाड्याच्या रकमा INR मध्ये आहेत.',
    roleAdministration: 'प्रशासन',
    manageAdminRoles: 'अॅडमिन भूमिका आणि प्रवेश परवानग्या व्यवस्थापित करा.',
    addRole: 'भूमिका जोडा',
    roleColumn: 'भूमिका',
    descriptionColumn: 'वर्णन',
    usersColumn: 'वापरकर्ते',
    statusColumn: 'स्थिती',
    actionsColumn: 'कृती',
    editRole: 'भूमिका संपादित करा',
    createRole: 'भूमिका तयार करा',
    roleName: 'भूमिकेचे नाव',
    roleNameRequired: 'भूमिकेचे नाव आवश्यक आहे.',
    roleNamePlaceholder: 'उदा. Operations',
    roleDescriptionPlaceholder: 'ही भूमिका काय व्यवस्थापित करू शकते ते वर्णन करा',
    permissions: 'परवानग्या',
    selectedCount: 'निवडलेले',
    uiDemoDataBackendPending: 'UI डेमो डेटा — बॅकएंड इंटिग्रेशन प्रलंबित आहे.',
    usersCount: 'वापरकर्ते',
    fullAccessAllAdminModules: 'सर्व अॅडमिन मॉड्यूल्सना पूर्ण प्रवेश.',
    manageDriversRidesLiveOperations: 'ड्रायव्हर, राइड आणि लाइव्ह ऑपरेशन्स व्यवस्थापित करा.',
    handleCustomerDriverSupport: 'ग्राहक आणि ड्रायव्हर सपोर्ट विनंत्या हाताळा.',
    errorTitle: 'त्रुटी',
    confirmLogout: 'लॉगआउटची पुष्टी करा',
    logoutMessage: 'तुम्हाला RideEasy Admin Panel मधून लॉगआउट करायचे आहे का?',
    logout: 'लॉगआउट',
    backToDrivers: 'ड्रायव्हर्सकडे परत जा',
    unableLoadVehicles: 'वाहने लोड करता आली नाहीत',
  },
}

const AdminLanguageContext = createContext(null)

export function AdminLanguageProvider({ children }) {
  const [language, setLanguage] = useState(
    () => localStorage.getItem('adminLanguage') || 'en'
  )

  const changeLanguage = (nextLanguage) => {
    const value = translations[nextLanguage] ? nextLanguage : 'en'
    setLanguage(value)
    localStorage.setItem('adminLanguage', value)
  }

  const value = useMemo(
    () => ({
      language,
      changeLanguage,
      t: translations[language] || translations.en,
    }),
    [language]
  )

  return (
    <AdminLanguageContext.Provider value={value}>
      {children}
    </AdminLanguageContext.Provider>
  )
}

export function useAdminLanguage() {
  const context = useContext(AdminLanguageContext)

  if (!context) {
    throw new Error(
      'useAdminLanguage must be used inside AdminLanguageProvider'
    )
  }

  return context
}
